// Sentinel RunControl (M8, ADR-021) — the Go orchestrator's gRPC contract.
// The brain reports per-node token deltas; the orchestrator reconciles them against the run's
// budget and may signal an abort (Control.abort). A model-INDEPENDENT hard kill (SIGTERM of the
// brain subprocess) is the backstop. Stubs are generated for Go + Python; this file's hash is
// asserted against the checked-in stubs (drift = build failure), mirroring persistence.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: runcontrol.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunControl_StartRun_FullMethodName    = "/sentinel.runcontrol.v1.RunControl/StartRun"
	RunControl_ReportEvent_FullMethodName = "/sentinel.runcontrol.v1.RunControl/ReportEvent"
	RunControl_Abort_FullMethodName       = "/sentinel.runcontrol.v1.RunControl/Abort"
	RunControl_Takeover_FullMethodName    = "/sentinel.runcontrol.v1.RunControl/Takeover"
	RunControl_Return_FullMethodName      = "/sentinel.runcontrol.v1.RunControl/Return"
)

// RunControlClient is the client API for RunControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunControlClient interface {
	// Register a run (limits set by the orchestrator from config/env).
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunReply, error)
	// brain -> orchestrator, once per node-step; the reply may instruct the brain to abort / degrade
	// (M9.8 F4, ADR-054: or to PAUSE for an operator takeover via Control.takeover).
	ReportEvent(ctx context.Context, in *RunEvent, opts ...grpc.CallOption) (*Control, error)
	// External abort (operator / deadline).
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortReply, error)
	// M9.8 F4 (ADR-054): operator co-pilot takeover/return. Takeover sets a per-run flag; the next
	// ReportEvent reply then carries Control.takeover=true, so the brain interrupt()s + persists at its
	// superstep boundary (paused; the human drives the live browser via CDP). Return clears the flag, and
	// the brain resumes the same checkpointer thread from exactly where it paused. External (UI/operator),
	// forwarded by the control-API over its WebSocket — modelled on Abort.
	Takeover(ctx context.Context, in *TakeoverRequest, opts ...grpc.CallOption) (*TakeoverReply, error)
	Return(ctx context.Context, in *ReturnRequest, opts ...grpc.CallOption) (*ReturnReply, error)
}

type runControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRunControlClient(cc grpc.ClientConnInterface) RunControlClient {
	return &runControlClient{cc}
}

func (c *runControlClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunReply)
	err := c.cc.Invoke(ctx, RunControl_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runControlClient) ReportEvent(ctx context.Context, in *RunEvent, opts ...grpc.CallOption) (*Control, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Control)
	err := c.cc.Invoke(ctx, RunControl_ReportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runControlClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortReply)
	err := c.cc.Invoke(ctx, RunControl_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runControlClient) Takeover(ctx context.Context, in *TakeoverRequest, opts ...grpc.CallOption) (*TakeoverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeoverReply)
	err := c.cc.Invoke(ctx, RunControl_Takeover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runControlClient) Return(ctx context.Context, in *ReturnRequest, opts ...grpc.CallOption) (*ReturnReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnReply)
	err := c.cc.Invoke(ctx, RunControl_Return_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunControlServer is the server API for RunControl service.
// All implementations must embed UnimplementedRunControlServer
// for forward compatibility.
type RunControlServer interface {
	// Register a run (limits set by the orchestrator from config/env).
	StartRun(context.Context, *StartRunRequest) (*StartRunReply, error)
	// brain -> orchestrator, once per node-step; the reply may instruct the brain to abort / degrade
	// (M9.8 F4, ADR-054: or to PAUSE for an operator takeover via Control.takeover).
	ReportEvent(context.Context, *RunEvent) (*Control, error)
	// External abort (operator / deadline).
	Abort(context.Context, *AbortRequest) (*AbortReply, error)
	// M9.8 F4 (ADR-054): operator co-pilot takeover/return. Takeover sets a per-run flag; the next
	// ReportEvent reply then carries Control.takeover=true, so the brain interrupt()s + persists at its
	// superstep boundary (paused; the human drives the live browser via CDP). Return clears the flag, and
	// the brain resumes the same checkpointer thread from exactly where it paused. External (UI/operator),
	// forwarded by the control-API over its WebSocket — modelled on Abort.
	Takeover(context.Context, *TakeoverRequest) (*TakeoverReply, error)
	Return(context.Context, *ReturnRequest) (*ReturnReply, error)
	mustEmbedUnimplementedRunControlServer()
}

// UnimplementedRunControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunControlServer struct{}

func (UnimplementedRunControlServer) StartRun(context.Context, *StartRunRequest) (*StartRunReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRunControlServer) ReportEvent(context.Context, *RunEvent) (*Control, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedRunControlServer) Abort(context.Context, *AbortRequest) (*AbortReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedRunControlServer) Takeover(context.Context, *TakeoverRequest) (*TakeoverReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Takeover not implemented")
}
func (UnimplementedRunControlServer) Return(context.Context, *ReturnRequest) (*ReturnReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Return not implemented")
}
func (UnimplementedRunControlServer) mustEmbedUnimplementedRunControlServer() {}
func (UnimplementedRunControlServer) testEmbeddedByValue()                    {}

// UnsafeRunControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunControlServer will
// result in compilation errors.
type UnsafeRunControlServer interface {
	mustEmbedUnimplementedRunControlServer()
}

func RegisterRunControlServer(s grpc.ServiceRegistrar, srv RunControlServer) {
	// If the following call panics, it indicates UnimplementedRunControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunControl_ServiceDesc, srv)
}

func _RunControl_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunControlServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunControl_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunControlServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunControl_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunControlServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunControl_ReportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunControlServer).ReportEvent(ctx, req.(*RunEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunControl_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunControlServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunControl_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunControlServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunControl_Takeover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunControlServer).Takeover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunControl_Takeover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunControlServer).Takeover(ctx, req.(*TakeoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunControl_Return_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunControlServer).Return(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunControl_Return_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunControlServer).Return(ctx, req.(*ReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunControl_ServiceDesc is the grpc.ServiceDesc for RunControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.runcontrol.v1.RunControl",
	HandlerType: (*RunControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RunControl_StartRun_Handler,
		},
		{
			MethodName: "ReportEvent",
			Handler:    _RunControl_ReportEvent_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _RunControl_Abort_Handler,
		},
		{
			MethodName: "Takeover",
			Handler:    _RunControl_Takeover_Handler,
		},
		{
			MethodName: "Return",
			Handler:    _RunControl_Return_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runcontrol.proto",
}
