// Sentinel RunControl (M8, ADR-021) — the Go orchestrator's gRPC contract.
// The brain reports per-node token deltas; the orchestrator reconciles them against the run's
// budget and may signal an abort (Control.abort). A model-INDEPENDENT hard kill (SIGTERM of the
// brain subprocess) is the backstop. Stubs are generated for Go + Python; this file's hash is
// asserted against the checked-in stubs (drift = build failure), mirroring persistence.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: runcontrol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRunRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PlanTokenLimit  int64                  `protobuf:"varint,2,opt,name=plan_token_limit,json=planTokenLimit,proto3" json:"plan_token_limit,omitempty"`
	HealTokenLimit  int64                  `protobuf:"varint,3,opt,name=heal_token_limit,json=healTokenLimit,proto3" json:"heal_token_limit,omitempty"`
	TotalTokenLimit int64                  `protobuf:"varint,4,opt,name=total_token_limit,json=totalTokenLimit,proto3" json:"total_token_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_runcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *StartRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartRunRequest) GetPlanTokenLimit() int64 {
	if x != nil {
		return x.PlanTokenLimit
	}
	return 0
}

func (x *StartRunRequest) GetHealTokenLimit() int64 {
	if x != nil {
		return x.HealTokenLimit
	}
	return 0
}

func (x *StartRunRequest) GetTotalTokenLimit() int64 {
	if x != nil {
		return x.TotalTokenLimit
	}
	return 0
}

type StartRunReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunReply) Reset() {
	*x = StartRunReply{}
	mi := &file_runcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunReply) ProtoMessage() {}

func (x *StartRunReply) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunReply.ProtoReflect.Descriptor instead.
func (*StartRunReply) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *StartRunReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RunEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Node             string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`                                      // LangGraph node name (plan / heal / ...)
	PromptTokens     int64                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"` // cumulative for the run
	CompletionTokens int64                  `protobuf:"varint,4,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // running | done | error
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_runcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RunEvent) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *RunEvent) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *RunEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abort         bool                   `protobuf:"varint,1,opt,name=abort,proto3" json:"abort,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_runcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *Control) GetAbort() bool {
	if x != nil {
		return x.Abort
	}
	return false
}

func (x *Control) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_runcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *AbortRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AbortRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortReply) Reset() {
	*x = AbortReply{}
	mi := &file_runcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortReply) ProtoMessage() {}

func (x *AbortReply) ProtoReflect() protoreflect.Message {
	mi := &file_runcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortReply.ProtoReflect.Descriptor instead.
func (*AbortReply) Descriptor() ([]byte, []int) {
	return file_runcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *AbortReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_runcontrol_proto protoreflect.FileDescriptor

const file_runcontrol_proto_rawDesc = "" +
	"\n" +
	"\x10runcontrol.proto\x12\x16sentinel.runcontrol.v1\"\xa8\x01\n" +
	"\x0fStartRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12(\n" +
	"\x10plan_token_limit\x18\x02 \x01(\x03R\x0eplanTokenLimit\x12(\n" +
	"\x10heal_token_limit\x18\x03 \x01(\x03R\x0ehealTokenLimit\x12*\n" +
	"\x11total_token_limit\x18\x04 \x01(\x03R\x0ftotalTokenLimit\"\x1f\n" +
	"\rStartRunReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x9f\x01\n" +
	"\bRunEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x04 \x01(\x03R\x10completionTokens\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"7\n" +
	"\aControl\x12\x14\n" +
	"\x05abort\x18\x01 \x01(\bR\x05abort\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\fAbortRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1c\n" +
	"\n" +
	"AbortReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x8d\x02\n" +
	"\n" +
	"RunControl\x12Z\n" +
	"\bStartRun\x12'.sentinel.runcontrol.v1.StartRunRequest\x1a%.sentinel.runcontrol.v1.StartRunReply\x12P\n" +
	"\vReportEvent\x12 .sentinel.runcontrol.v1.RunEvent\x1a\x1f.sentinel.runcontrol.v1.Control\x12Q\n" +
	"\x05Abort\x12$.sentinel.runcontrol.v1.AbortRequest\x1a\".sentinel.runcontrol.v1.AbortReplyB<Z:github.com/AlexGromer/sentinel/internal/orchestrator/pb;pbb\x06proto3"

var (
	file_runcontrol_proto_rawDescOnce sync.Once
	file_runcontrol_proto_rawDescData []byte
)

func file_runcontrol_proto_rawDescGZIP() []byte {
	file_runcontrol_proto_rawDescOnce.Do(func() {
		file_runcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runcontrol_proto_rawDesc), len(file_runcontrol_proto_rawDesc)))
	})
	return file_runcontrol_proto_rawDescData
}

var file_runcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runcontrol_proto_goTypes = []any{
	(*StartRunRequest)(nil), // 0: sentinel.runcontrol.v1.StartRunRequest
	(*StartRunReply)(nil),   // 1: sentinel.runcontrol.v1.StartRunReply
	(*RunEvent)(nil),        // 2: sentinel.runcontrol.v1.RunEvent
	(*Control)(nil),         // 3: sentinel.runcontrol.v1.Control
	(*AbortRequest)(nil),    // 4: sentinel.runcontrol.v1.AbortRequest
	(*AbortReply)(nil),      // 5: sentinel.runcontrol.v1.AbortReply
}
var file_runcontrol_proto_depIdxs = []int32{
	0, // 0: sentinel.runcontrol.v1.RunControl.StartRun:input_type -> sentinel.runcontrol.v1.StartRunRequest
	2, // 1: sentinel.runcontrol.v1.RunControl.ReportEvent:input_type -> sentinel.runcontrol.v1.RunEvent
	4, // 2: sentinel.runcontrol.v1.RunControl.Abort:input_type -> sentinel.runcontrol.v1.AbortRequest
	1, // 3: sentinel.runcontrol.v1.RunControl.StartRun:output_type -> sentinel.runcontrol.v1.StartRunReply
	3, // 4: sentinel.runcontrol.v1.RunControl.ReportEvent:output_type -> sentinel.runcontrol.v1.Control
	5, // 5: sentinel.runcontrol.v1.RunControl.Abort:output_type -> sentinel.runcontrol.v1.AbortReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runcontrol_proto_init() }
func file_runcontrol_proto_init() {
	if File_runcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runcontrol_proto_rawDesc), len(file_runcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runcontrol_proto_goTypes,
		DependencyIndexes: file_runcontrol_proto_depIdxs,
		MessageInfos:      file_runcontrol_proto_msgTypes,
	}.Build()
	File_runcontrol_proto = out.File
	file_runcontrol_proto_goTypes = nil
	file_runcontrol_proto_depIdxs = nil
}
