# AUTO-GENERATED by scripts/gen-brew-formula.sh (release.yml homebrew job, on each v* tag). Do not hand-edit.
# This repo is its own tap:  brew tap AlexGromer/sentinel https://github.com/AlexGromer/sentinel  then  brew install sentinel
# Pre-first-release the committed values are a v0.0.0 / zero-sha256 placeholder that fails the brew checksum
# on purpose (the maintainer-gated E2E boundary as M11.1); each signed release rewrites version + url + sha256.
class Sentinel < Formula
  desc "Autonomous self-healing UI-testing agent — agentctl control-plane CLI"
  homepage "https://github.com/AlexGromer/sentinel"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/AlexGromer/sentinel/releases/download/v0.2.1/sentinel-v0.2.1-darwin-arm64.tar.gz"
      sha256 "9d4f38744710054244f96ee7e5f182690431d318e71181927d223889c0188248"
    end
    on_intel do
      url "https://github.com/AlexGromer/sentinel/releases/download/v0.2.1/sentinel-v0.2.1-darwin-amd64.tar.gz"
      sha256 "eab8a30278c037c924ec6c83ec5294b3d215f480352cce0d18d78f8aa9fb66fb"
    end
  end

  def install
    bin.install "agentctl"
  end

  test do
    assert_match(/\d/, shell_output("#{bin}/agentctl version"))
  end
end
