# AUTO-GENERATED by scripts/gen-brew-formula.sh (release.yml homebrew job, on each v* tag). Do not hand-edit.
# This repo is its own tap:  brew tap AlexGromer/sentinel https://github.com/AlexGromer/sentinel  then  brew install sentinel
# Pre-first-release the committed values are a v0.0.0 / zero-sha256 placeholder that fails the brew checksum
# on purpose (the maintainer-gated E2E boundary as M11.1); each signed release rewrites version + url + sha256.
class Sentinel < Formula
  desc "Autonomous self-healing UI-testing agent — agentctl control-plane CLI"
  homepage "https://github.com/AlexGromer/sentinel"
  version "0.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/AlexGromer/sentinel/releases/download/v0.0.0/sentinel-v0.0.0-darwin-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/AlexGromer/sentinel/releases/download/v0.0.0/sentinel-v0.0.0-darwin-amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "agentctl"
  end

  test do
    assert_match(/\d/, shell_output("#{bin}/agentctl version"))
  end
end
