// Sentinel PersistenceService (M2b-1) — the Go store-gateway's gRPC contract.
// Mirrors brain/store.py 1:1 so brain/store.py can become a thin gRPC client (ADR-015).
// Stubs are generated for Go + Python in CI; this file's hash is asserted against the
// checked-in stubs (drift = build failure).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: persistence.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersistenceService_Lookup_FullMethodName          = "/sentinel.persistence.v1.PersistenceService/Lookup"
	PersistenceService_EvictStale_FullMethodName      = "/sentinel.persistence.v1.PersistenceService/EvictStale"
	PersistenceService_SaveLocator_FullMethodName     = "/sentinel.persistence.v1.PersistenceService/SaveLocator"
	PersistenceService_BumpUsed_FullMethodName        = "/sentinel.persistence.v1.PersistenceService/BumpUsed"
	PersistenceService_AppendAudit_FullMethodName     = "/sentinel.persistence.v1.PersistenceService/AppendAudit"
	PersistenceService_SaveGolden_FullMethodName      = "/sentinel.persistence.v1.PersistenceService/SaveGolden"
	PersistenceService_GetGolden_FullMethodName       = "/sentinel.persistence.v1.PersistenceService/GetGolden"
	PersistenceService_RecordStep_FullMethodName      = "/sentinel.persistence.v1.PersistenceService/RecordStep"
	PersistenceService_IsQuarantined_FullMethodName   = "/sentinel.persistence.v1.PersistenceService/IsQuarantined"
	PersistenceService_ClearQuarantine_FullMethodName = "/sentinel.persistence.v1.PersistenceService/ClearQuarantine"
	PersistenceService_AuditRows_FullMethodName       = "/sentinel.persistence.v1.PersistenceService/AuditRows"
)

// PersistenceServiceClient is the client API for PersistenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersistenceServiceClient interface {
	Lookup(ctx context.Context, in *LocatorKey, opts ...grpc.CallOption) (*LocatorRecord, error)
	EvictStale(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*Empty, error)
	SaveLocator(ctx context.Context, in *LocatorRecord, opts ...grpc.CallOption) (*Empty, error)
	BumpUsed(ctx context.Context, in *LocatorKey, opts ...grpc.CallOption) (*Empty, error)
	AppendAudit(ctx context.Context, in *AuditRow, opts ...grpc.CallOption) (*Empty, error)
	SaveGolden(ctx context.Context, in *Golden, opts ...grpc.CallOption) (*Empty, error)
	GetGolden(ctx context.Context, in *PageKey, opts ...grpc.CallOption) (*Golden, error)
	RecordStep(ctx context.Context, in *StepResult, opts ...grpc.CallOption) (*Quarantine, error)
	IsQuarantined(ctx context.Context, in *StepKey, opts ...grpc.CallOption) (*Quarantine, error)
	ClearQuarantine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error)
	AuditRows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuditRowsReply, error)
}

type persistenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceServiceClient(cc grpc.ClientConnInterface) PersistenceServiceClient {
	return &persistenceServiceClient{cc}
}

func (c *persistenceServiceClient) Lookup(ctx context.Context, in *LocatorKey, opts ...grpc.CallOption) (*LocatorRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocatorRecord)
	err := c.cc.Invoke(ctx, PersistenceService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) EvictStale(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PersistenceService_EvictStale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) SaveLocator(ctx context.Context, in *LocatorRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PersistenceService_SaveLocator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) BumpUsed(ctx context.Context, in *LocatorKey, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PersistenceService_BumpUsed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) AppendAudit(ctx context.Context, in *AuditRow, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PersistenceService_AppendAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) SaveGolden(ctx context.Context, in *Golden, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PersistenceService_SaveGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetGolden(ctx context.Context, in *PageKey, opts ...grpc.CallOption) (*Golden, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Golden)
	err := c.cc.Invoke(ctx, PersistenceService_GetGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) RecordStep(ctx context.Context, in *StepResult, opts ...grpc.CallOption) (*Quarantine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quarantine)
	err := c.cc.Invoke(ctx, PersistenceService_RecordStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) IsQuarantined(ctx context.Context, in *StepKey, opts ...grpc.CallOption) (*Quarantine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quarantine)
	err := c.cc.Invoke(ctx, PersistenceService_IsQuarantined_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) ClearQuarantine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Count, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Count)
	err := c.cc.Invoke(ctx, PersistenceService_ClearQuarantine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) AuditRows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuditRowsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditRowsReply)
	err := c.cc.Invoke(ctx, PersistenceService_AuditRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServiceServer is the server API for PersistenceService service.
// All implementations must embed UnimplementedPersistenceServiceServer
// for forward compatibility.
type PersistenceServiceServer interface {
	Lookup(context.Context, *LocatorKey) (*LocatorRecord, error)
	EvictStale(context.Context, *EvictRequest) (*Empty, error)
	SaveLocator(context.Context, *LocatorRecord) (*Empty, error)
	BumpUsed(context.Context, *LocatorKey) (*Empty, error)
	AppendAudit(context.Context, *AuditRow) (*Empty, error)
	SaveGolden(context.Context, *Golden) (*Empty, error)
	GetGolden(context.Context, *PageKey) (*Golden, error)
	RecordStep(context.Context, *StepResult) (*Quarantine, error)
	IsQuarantined(context.Context, *StepKey) (*Quarantine, error)
	ClearQuarantine(context.Context, *Empty) (*Count, error)
	AuditRows(context.Context, *Empty) (*AuditRowsReply, error)
	mustEmbedUnimplementedPersistenceServiceServer()
}

// UnimplementedPersistenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersistenceServiceServer struct{}

func (UnimplementedPersistenceServiceServer) Lookup(context.Context, *LocatorKey) (*LocatorRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedPersistenceServiceServer) EvictStale(context.Context, *EvictRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictStale not implemented")
}
func (UnimplementedPersistenceServiceServer) SaveLocator(context.Context, *LocatorRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveLocator not implemented")
}
func (UnimplementedPersistenceServiceServer) BumpUsed(context.Context, *LocatorKey) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BumpUsed not implemented")
}
func (UnimplementedPersistenceServiceServer) AppendAudit(context.Context, *AuditRow) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendAudit not implemented")
}
func (UnimplementedPersistenceServiceServer) SaveGolden(context.Context, *Golden) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveGolden not implemented")
}
func (UnimplementedPersistenceServiceServer) GetGolden(context.Context, *PageKey) (*Golden, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGolden not implemented")
}
func (UnimplementedPersistenceServiceServer) RecordStep(context.Context, *StepResult) (*Quarantine, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordStep not implemented")
}
func (UnimplementedPersistenceServiceServer) IsQuarantined(context.Context, *StepKey) (*Quarantine, error) {
	return nil, status.Error(codes.Unimplemented, "method IsQuarantined not implemented")
}
func (UnimplementedPersistenceServiceServer) ClearQuarantine(context.Context, *Empty) (*Count, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearQuarantine not implemented")
}
func (UnimplementedPersistenceServiceServer) AuditRows(context.Context, *Empty) (*AuditRowsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditRows not implemented")
}
func (UnimplementedPersistenceServiceServer) mustEmbedUnimplementedPersistenceServiceServer() {}
func (UnimplementedPersistenceServiceServer) testEmbeddedByValue()                            {}

// UnsafePersistenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServiceServer will
// result in compilation errors.
type UnsafePersistenceServiceServer interface {
	mustEmbedUnimplementedPersistenceServiceServer()
}

func RegisterPersistenceServiceServer(s grpc.ServiceRegistrar, srv PersistenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPersistenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersistenceService_ServiceDesc, srv)
}

func _PersistenceService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocatorKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).Lookup(ctx, req.(*LocatorKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_EvictStale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).EvictStale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_EvictStale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).EvictStale(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_SaveLocator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocatorRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).SaveLocator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_SaveLocator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).SaveLocator(ctx, req.(*LocatorRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_BumpUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocatorKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).BumpUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_BumpUsed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).BumpUsed(ctx, req.(*LocatorKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_AppendAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).AppendAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_AppendAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).AppendAudit(ctx, req.(*AuditRow))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_SaveGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Golden)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).SaveGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_SaveGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).SaveGolden(ctx, req.(*Golden))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetGolden(ctx, req.(*PageKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_RecordStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).RecordStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_RecordStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).RecordStep(ctx, req.(*StepResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_IsQuarantined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).IsQuarantined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_IsQuarantined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).IsQuarantined(ctx, req.(*StepKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_ClearQuarantine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).ClearQuarantine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_ClearQuarantine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).ClearQuarantine(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_AuditRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).AuditRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_AuditRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).AuditRows(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PersistenceService_ServiceDesc is the grpc.ServiceDesc for PersistenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.persistence.v1.PersistenceService",
	HandlerType: (*PersistenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _PersistenceService_Lookup_Handler,
		},
		{
			MethodName: "EvictStale",
			Handler:    _PersistenceService_EvictStale_Handler,
		},
		{
			MethodName: "SaveLocator",
			Handler:    _PersistenceService_SaveLocator_Handler,
		},
		{
			MethodName: "BumpUsed",
			Handler:    _PersistenceService_BumpUsed_Handler,
		},
		{
			MethodName: "AppendAudit",
			Handler:    _PersistenceService_AppendAudit_Handler,
		},
		{
			MethodName: "SaveGolden",
			Handler:    _PersistenceService_SaveGolden_Handler,
		},
		{
			MethodName: "GetGolden",
			Handler:    _PersistenceService_GetGolden_Handler,
		},
		{
			MethodName: "RecordStep",
			Handler:    _PersistenceService_RecordStep_Handler,
		},
		{
			MethodName: "IsQuarantined",
			Handler:    _PersistenceService_IsQuarantined_Handler,
		},
		{
			MethodName: "ClearQuarantine",
			Handler:    _PersistenceService_ClearQuarantine_Handler,
		},
		{
			MethodName: "AuditRows",
			Handler:    _PersistenceService_AuditRows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistence.proto",
}
