// Sentinel PersistenceService (M2b-1) — the Go store-gateway's gRPC contract.
// Mirrors brain/store.py 1:1 so brain/store.py can become a thin gRPC client (ADR-015).
// Stubs are generated for Go + Python in CI; this file's hash is asserted against the
// checked-in stubs (drift = build failure).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: persistence.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_persistence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{0}
}

// --- healed locators (M2) ---------------------------------------------------
type LocatorKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PagePath       string                 `protobuf:"bytes,1,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	SemanticId     string                 `protobuf:"bytes,2,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	DomSubtreeHash string                 `protobuf:"bytes,3,opt,name=dom_subtree_hash,json=domSubtreeHash,proto3" json:"dom_subtree_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocatorKey) Reset() {
	*x = LocatorKey{}
	mi := &file_persistence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocatorKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocatorKey) ProtoMessage() {}

func (x *LocatorKey) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocatorKey.ProtoReflect.Descriptor instead.
func (*LocatorKey) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{1}
}

func (x *LocatorKey) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *LocatorKey) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *LocatorKey) GetDomSubtreeHash() string {
	if x != nil {
		return x.DomSubtreeHash
	}
	return ""
}

type LocatorRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PagePath       string                 `protobuf:"bytes,1,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	SemanticId     string                 `protobuf:"bytes,2,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	Strategy       string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Value          string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // opaque JSON locator dict
	Confidence     float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DomSubtreeHash string                 `protobuf:"bytes,6,opt,name=dom_subtree_hash,json=domSubtreeHash,proto3" json:"dom_subtree_hash,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // active | flagged | deprecated
	Found          bool                   `protobuf:"varint,8,opt,name=found,proto3" json:"found,omitempty"`  // false => no active record
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocatorRecord) Reset() {
	*x = LocatorRecord{}
	mi := &file_persistence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocatorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocatorRecord) ProtoMessage() {}

func (x *LocatorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocatorRecord.ProtoReflect.Descriptor instead.
func (*LocatorRecord) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{2}
}

func (x *LocatorRecord) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *LocatorRecord) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *LocatorRecord) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *LocatorRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LocatorRecord) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LocatorRecord) GetDomSubtreeHash() string {
	if x != nil {
		return x.DomSubtreeHash
	}
	return ""
}

func (x *LocatorRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LocatorRecord) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type EvictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PagePath      string                 `protobuf:"bytes,1,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	SemanticId    string                 `protobuf:"bytes,2,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,3,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRequest) Reset() {
	*x = EvictRequest{}
	mi := &file_persistence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRequest) ProtoMessage() {}

func (x *EvictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRequest.ProtoReflect.Descriptor instead.
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{3}
}

func (x *EvictRequest) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *EvictRequest) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *EvictRequest) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

type AuditRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          int64                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	SemanticId    string                 `protobuf:"bytes,3,opt,name=semantic_id,json=semanticId,proto3" json:"semantic_id,omitempty"`
	PagePath      string                 `protobuf:"bytes,4,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	Strategy      string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Original      string                 `protobuf:"bytes,6,opt,name=original,proto3" json:"original,omitempty"`
	Healed        string                 `protobuf:"bytes,7,opt,name=healed,proto3" json:"healed,omitempty"`
	Confidence    float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Outcome       string                 `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	DomHash       string                 `protobuf:"bytes,10,opt,name=dom_hash,json=domHash,proto3" json:"dom_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRow) Reset() {
	*x = AuditRow{}
	mi := &file_persistence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRow) ProtoMessage() {}

func (x *AuditRow) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRow.ProtoReflect.Descriptor instead.
func (*AuditRow) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{4}
}

func (x *AuditRow) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AuditRow) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *AuditRow) GetSemanticId() string {
	if x != nil {
		return x.SemanticId
	}
	return ""
}

func (x *AuditRow) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *AuditRow) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *AuditRow) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *AuditRow) GetHealed() string {
	if x != nil {
		return x.Healed
	}
	return ""
}

func (x *AuditRow) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AuditRow) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditRow) GetDomHash() string {
	if x != nil {
		return x.DomHash
	}
	return ""
}

type AuditRowsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*AuditRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRowsReply) Reset() {
	*x = AuditRowsReply{}
	mi := &file_persistence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRowsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRowsReply) ProtoMessage() {}

func (x *AuditRowsReply) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRowsReply.ProtoReflect.Descriptor instead.
func (*AuditRowsReply) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{5}
}

func (x *AuditRowsReply) GetRows() []*AuditRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// --- golden baselines (M3) --------------------------------------------------
type Golden struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PageKey        string                 `protobuf:"bytes,1,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
	A11YHash       string                 `protobuf:"bytes,2,opt,name=a11y_hash,json=a11yHash,proto3" json:"a11y_hash,omitempty"`
	ScreenshotHash string                 `protobuf:"bytes,3,opt,name=screenshot_hash,json=screenshotHash,proto3" json:"screenshot_hash,omitempty"`
	Found          bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Golden) Reset() {
	*x = Golden{}
	mi := &file_persistence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Golden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Golden) ProtoMessage() {}

func (x *Golden) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Golden.ProtoReflect.Descriptor instead.
func (*Golden) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{6}
}

func (x *Golden) GetPageKey() string {
	if x != nil {
		return x.PageKey
	}
	return ""
}

func (x *Golden) GetA11YHash() string {
	if x != nil {
		return x.A11YHash
	}
	return ""
}

func (x *Golden) GetScreenshotHash() string {
	if x != nil {
		return x.ScreenshotHash
	}
	return ""
}

func (x *Golden) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PageKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageKey       string                 `protobuf:"bytes,1,opt,name=page_key,json=pageKey,proto3" json:"page_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageKey) Reset() {
	*x = PageKey{}
	mi := &file_persistence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageKey) ProtoMessage() {}

func (x *PageKey) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageKey.ProtoReflect.Descriptor instead.
func (*PageKey) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{7}
}

func (x *PageKey) GetPageKey() string {
	if x != nil {
		return x.PageKey
	}
	return ""
}

// --- flake quarantine (M3) --------------------------------------------------
type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StepKey       string                 `protobuf:"bytes,2,opt,name=step_key,json=stepKey,proto3" json:"step_key,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	AutSha        string                 `protobuf:"bytes,4,opt,name=aut_sha,json=autSha,proto3" json:"aut_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_persistence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{8}
}

func (x *StepResult) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *StepResult) GetStepKey() string {
	if x != nil {
		return x.StepKey
	}
	return ""
}

func (x *StepResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *StepResult) GetAutSha() string {
	if x != nil {
		return x.AutSha
	}
	return ""
}

type StepKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StepKey       string                 `protobuf:"bytes,2,opt,name=step_key,json=stepKey,proto3" json:"step_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepKey) Reset() {
	*x = StepKey{}
	mi := &file_persistence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepKey) ProtoMessage() {}

func (x *StepKey) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepKey.ProtoReflect.Descriptor instead.
func (*StepKey) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{9}
}

func (x *StepKey) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *StepKey) GetStepKey() string {
	if x != nil {
		return x.StepKey
	}
	return ""
}

type Quarantine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quarantined   bool                   `protobuf:"varint,1,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quarantine) Reset() {
	*x = Quarantine{}
	mi := &file_persistence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quarantine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quarantine) ProtoMessage() {}

func (x *Quarantine) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quarantine.ProtoReflect.Descriptor instead.
func (*Quarantine) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{10}
}

func (x *Quarantine) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

type Count struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_persistence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_persistence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_persistence_proto_rawDescGZIP(), []int{11}
}

func (x *Count) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

var File_persistence_proto protoreflect.FileDescriptor

const file_persistence_proto_rawDesc = "" +
	"\n" +
	"\x11persistence.proto\x12\x17sentinel.persistence.v1\"\a\n" +
	"\x05Empty\"t\n" +
	"\n" +
	"LocatorKey\x12\x1b\n" +
	"\tpage_path\x18\x01 \x01(\tR\bpagePath\x12\x1f\n" +
	"\vsemantic_id\x18\x02 \x01(\tR\n" +
	"semanticId\x12(\n" +
	"\x10dom_subtree_hash\x18\x03 \x01(\tR\x0edomSubtreeHash\"\xf7\x01\n" +
	"\rLocatorRecord\x12\x1b\n" +
	"\tpage_path\x18\x01 \x01(\tR\bpagePath\x12\x1f\n" +
	"\vsemantic_id\x18\x02 \x01(\tR\n" +
	"semanticId\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12(\n" +
	"\x10dom_subtree_hash\x18\x06 \x01(\tR\x0edomSubtreeHash\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05found\x18\b \x01(\bR\x05found\"o\n" +
	"\fEvictRequest\x12\x1b\n" +
	"\tpage_path\x18\x01 \x01(\tR\bpagePath\x12\x1f\n" +
	"\vsemantic_id\x18\x02 \x01(\tR\n" +
	"semanticId\x12!\n" +
	"\fcurrent_hash\x18\x03 \x01(\tR\vcurrentHash\"\x98\x02\n" +
	"\bAuditRow\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x03R\x04step\x12\x1f\n" +
	"\vsemantic_id\x18\x03 \x01(\tR\n" +
	"semanticId\x12\x1b\n" +
	"\tpage_path\x18\x04 \x01(\tR\bpagePath\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12\x1a\n" +
	"\boriginal\x18\x06 \x01(\tR\boriginal\x12\x16\n" +
	"\x06healed\x18\a \x01(\tR\x06healed\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\aoutcome\x18\t \x01(\tR\aoutcome\x12\x19\n" +
	"\bdom_hash\x18\n" +
	" \x01(\tR\adomHash\"G\n" +
	"\x0eAuditRowsReply\x125\n" +
	"\x04rows\x18\x01 \x03(\v2!.sentinel.persistence.v1.AuditRowR\x04rows\"\x7f\n" +
	"\x06Golden\x12\x19\n" +
	"\bpage_key\x18\x01 \x01(\tR\apageKey\x12\x1b\n" +
	"\ta11y_hash\x18\x02 \x01(\tR\ba11yHash\x12'\n" +
	"\x0fscreenshot_hash\x18\x03 \x01(\tR\x0escreenshotHash\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"$\n" +
	"\aPageKey\x12\x19\n" +
	"\bpage_key\x18\x01 \x01(\tR\apageKey\"q\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x19\n" +
	"\bstep_key\x18\x02 \x01(\tR\astepKey\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x17\n" +
	"\aaut_sha\x18\x04 \x01(\tR\x06autSha\"=\n" +
	"\aStepKey\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x19\n" +
	"\bstep_key\x18\x02 \x01(\tR\astepKey\".\n" +
	"\n" +
	"Quarantine\x12 \n" +
	"\vquarantined\x18\x01 \x01(\bR\vquarantined\"\x15\n" +
	"\x05Count\x12\f\n" +
	"\x01n\x18\x01 \x01(\x03R\x01n2\xb2\a\n" +
	"\x12PersistenceService\x12U\n" +
	"\x06Lookup\x12#.sentinel.persistence.v1.LocatorKey\x1a&.sentinel.persistence.v1.LocatorRecord\x12S\n" +
	"\n" +
	"EvictStale\x12%.sentinel.persistence.v1.EvictRequest\x1a\x1e.sentinel.persistence.v1.Empty\x12U\n" +
	"\vSaveLocator\x12&.sentinel.persistence.v1.LocatorRecord\x1a\x1e.sentinel.persistence.v1.Empty\x12O\n" +
	"\bBumpUsed\x12#.sentinel.persistence.v1.LocatorKey\x1a\x1e.sentinel.persistence.v1.Empty\x12P\n" +
	"\vAppendAudit\x12!.sentinel.persistence.v1.AuditRow\x1a\x1e.sentinel.persistence.v1.Empty\x12M\n" +
	"\n" +
	"SaveGolden\x12\x1f.sentinel.persistence.v1.Golden\x1a\x1e.sentinel.persistence.v1.Empty\x12N\n" +
	"\tGetGolden\x12 .sentinel.persistence.v1.PageKey\x1a\x1f.sentinel.persistence.v1.Golden\x12V\n" +
	"\n" +
	"RecordStep\x12#.sentinel.persistence.v1.StepResult\x1a#.sentinel.persistence.v1.Quarantine\x12V\n" +
	"\rIsQuarantined\x12 .sentinel.persistence.v1.StepKey\x1a#.sentinel.persistence.v1.Quarantine\x12Q\n" +
	"\x0fClearQuarantine\x12\x1e.sentinel.persistence.v1.Empty\x1a\x1e.sentinel.persistence.v1.Count\x12T\n" +
	"\tAuditRows\x12\x1e.sentinel.persistence.v1.Empty\x1a'.sentinel.persistence.v1.AuditRowsReplyB5Z3github.com/AlexGromer/sentinel/internal/store/pb;pbb\x06proto3"

var (
	file_persistence_proto_rawDescOnce sync.Once
	file_persistence_proto_rawDescData []byte
)

func file_persistence_proto_rawDescGZIP() []byte {
	file_persistence_proto_rawDescOnce.Do(func() {
		file_persistence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_persistence_proto_rawDesc), len(file_persistence_proto_rawDesc)))
	})
	return file_persistence_proto_rawDescData
}

var file_persistence_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_persistence_proto_goTypes = []any{
	(*Empty)(nil),          // 0: sentinel.persistence.v1.Empty
	(*LocatorKey)(nil),     // 1: sentinel.persistence.v1.LocatorKey
	(*LocatorRecord)(nil),  // 2: sentinel.persistence.v1.LocatorRecord
	(*EvictRequest)(nil),   // 3: sentinel.persistence.v1.EvictRequest
	(*AuditRow)(nil),       // 4: sentinel.persistence.v1.AuditRow
	(*AuditRowsReply)(nil), // 5: sentinel.persistence.v1.AuditRowsReply
	(*Golden)(nil),         // 6: sentinel.persistence.v1.Golden
	(*PageKey)(nil),        // 7: sentinel.persistence.v1.PageKey
	(*StepResult)(nil),     // 8: sentinel.persistence.v1.StepResult
	(*StepKey)(nil),        // 9: sentinel.persistence.v1.StepKey
	(*Quarantine)(nil),     // 10: sentinel.persistence.v1.Quarantine
	(*Count)(nil),          // 11: sentinel.persistence.v1.Count
}
var file_persistence_proto_depIdxs = []int32{
	4,  // 0: sentinel.persistence.v1.AuditRowsReply.rows:type_name -> sentinel.persistence.v1.AuditRow
	1,  // 1: sentinel.persistence.v1.PersistenceService.Lookup:input_type -> sentinel.persistence.v1.LocatorKey
	3,  // 2: sentinel.persistence.v1.PersistenceService.EvictStale:input_type -> sentinel.persistence.v1.EvictRequest
	2,  // 3: sentinel.persistence.v1.PersistenceService.SaveLocator:input_type -> sentinel.persistence.v1.LocatorRecord
	1,  // 4: sentinel.persistence.v1.PersistenceService.BumpUsed:input_type -> sentinel.persistence.v1.LocatorKey
	4,  // 5: sentinel.persistence.v1.PersistenceService.AppendAudit:input_type -> sentinel.persistence.v1.AuditRow
	6,  // 6: sentinel.persistence.v1.PersistenceService.SaveGolden:input_type -> sentinel.persistence.v1.Golden
	7,  // 7: sentinel.persistence.v1.PersistenceService.GetGolden:input_type -> sentinel.persistence.v1.PageKey
	8,  // 8: sentinel.persistence.v1.PersistenceService.RecordStep:input_type -> sentinel.persistence.v1.StepResult
	9,  // 9: sentinel.persistence.v1.PersistenceService.IsQuarantined:input_type -> sentinel.persistence.v1.StepKey
	0,  // 10: sentinel.persistence.v1.PersistenceService.ClearQuarantine:input_type -> sentinel.persistence.v1.Empty
	0,  // 11: sentinel.persistence.v1.PersistenceService.AuditRows:input_type -> sentinel.persistence.v1.Empty
	2,  // 12: sentinel.persistence.v1.PersistenceService.Lookup:output_type -> sentinel.persistence.v1.LocatorRecord
	0,  // 13: sentinel.persistence.v1.PersistenceService.EvictStale:output_type -> sentinel.persistence.v1.Empty
	0,  // 14: sentinel.persistence.v1.PersistenceService.SaveLocator:output_type -> sentinel.persistence.v1.Empty
	0,  // 15: sentinel.persistence.v1.PersistenceService.BumpUsed:output_type -> sentinel.persistence.v1.Empty
	0,  // 16: sentinel.persistence.v1.PersistenceService.AppendAudit:output_type -> sentinel.persistence.v1.Empty
	0,  // 17: sentinel.persistence.v1.PersistenceService.SaveGolden:output_type -> sentinel.persistence.v1.Empty
	6,  // 18: sentinel.persistence.v1.PersistenceService.GetGolden:output_type -> sentinel.persistence.v1.Golden
	10, // 19: sentinel.persistence.v1.PersistenceService.RecordStep:output_type -> sentinel.persistence.v1.Quarantine
	10, // 20: sentinel.persistence.v1.PersistenceService.IsQuarantined:output_type -> sentinel.persistence.v1.Quarantine
	11, // 21: sentinel.persistence.v1.PersistenceService.ClearQuarantine:output_type -> sentinel.persistence.v1.Count
	5,  // 22: sentinel.persistence.v1.PersistenceService.AuditRows:output_type -> sentinel.persistence.v1.AuditRowsReply
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_persistence_proto_init() }
func file_persistence_proto_init() {
	if File_persistence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_persistence_proto_rawDesc), len(file_persistence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_persistence_proto_goTypes,
		DependencyIndexes: file_persistence_proto_depIdxs,
		MessageInfos:      file_persistence_proto_msgTypes,
	}.Build()
	File_persistence_proto = out.File
	file_persistence_proto_goTypes = nil
	file_persistence_proto_depIdxs = nil
}
