// Sentinel StoreService (M13, ADR-049/050) — the store-gateway's 5-domain persistence contract,
// layered on top of the legacy heal/trust PersistenceService (persistence.proto) in the SAME package
// + go_package so both services live in one `pb` package and one single-writer DB (ADR-007).
// SQLite-first (portable `ON CONFLICT` SQL); a Postgres backend slots in later behind STORE_DSN
// (M13-service, M11/ADR-053). Stubs are generated for Go + Python; drift = build failure.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: store.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- runs (persist control-API's in-memory run map; survives restart) --------
type RunRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // M13: the runs<->chats join (today only in argv, lost on restart)
	Mode           string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`                                           // explore | goal | describe | replay | baseline | chat
	Target         string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Planner        string                 `protobuf:"bytes,5,opt,name=planner,proto3" json:"planner,omitempty"`
	State          string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"` // running | done | failed
	ExitCode       int64                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ArtifactDir    string                 `protobuf:"bytes,8,opt,name=artifact_dir,json=artifactDir,proto3" json:"artifact_dir,omitempty"`
	Error          string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt      string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`    // RFC3339
	FinishedAt     string                 `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // RFC3339 ("" while running)
	Found          bool                   `protobuf:"varint,12,opt,name=found,proto3" json:"found,omitempty"`                            // false => no such run (GetRun)
	// ADR-109: the local account that owns this row. EMPTY means unowned, which is what every row
	// written before identity existed carries — and what a single-team install keeps carrying, because
	// identity is OPT-IN: with no users created, nothing is scoped and the deployment behaves exactly
	// as it did. Scoping a store that has no subjects would break the one-team install that open-core
	// exists to serve.
	Owner         string `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRecord) Reset() {
	*x = RunRecord{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRecord) ProtoMessage() {}

func (x *RunRecord) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRecord.ProtoReflect.Descriptor instead.
func (*RunRecord) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *RunRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRecord) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RunRecord) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RunRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunRecord) GetPlanner() string {
	if x != nil {
		return x.Planner
	}
	return ""
}

func (x *RunRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunRecord) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunRecord) GetArtifactDir() string {
	if x != nil {
		return x.ArtifactDir
	}
	return ""
}

func (x *RunRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunRecord) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RunRecord) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *RunRecord) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RunRecord) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type RunId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunId) Reset() {
	*x = RunId{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunId) ProtoMessage() {}

func (x *RunId) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunId.ProtoReflect.Descriptor instead.
func (*RunId) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *RunId) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 0 => a sane default cap
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // "" => any
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109: "" => every row (a machine token); otherwise only this account's
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsReq) Reset() {
	*x = ListRunsReq{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsReq) ProtoMessage() {}

func (x *ListRunsReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsReq.ProtoReflect.Descriptor instead.
func (*ListRunsReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *ListRunsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRunsReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListRunsReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type RunList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunRecord           `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunList) Reset() {
	*x = RunList{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunList) ProtoMessage() {}

func (x *RunList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunList.ProtoReflect.Descriptor instead.
func (*RunList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{3}
}

func (x *RunList) GetRuns() []*RunRecord {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *RunList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- scenarios / tests (index plan.json/scenario.json; promote -> test) ------
type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	RunMode       string                 `protobuf:"bytes,4,opt,name=run_mode,json=runMode,proto3" json:"run_mode,omitempty"`       // goal | describe
	PlanHash      string                 `protobuf:"bytes,5,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"`    // brain/state.py:canonical_plan_hash
	StepsJson     string                 `protobuf:"bytes,6,opt,name=steps_json,json=stepsJson,proto3" json:"steps_json,omitempty"` // opaque grounded-steps JSON
	Unmatched     int64                  `protobuf:"varint,7,opt,name=unmatched,proto3" json:"unmatched,omitempty"`
	Tags          string                 `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"` // comma-separated
	SourceRunId   string                 `protobuf:"bytes,9,opt,name=source_run_id,json=sourceRunId,proto3" json:"source_run_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Found         bool                   `protobuf:"varint,11,opt,name=found,proto3" json:"found,omitempty"`
	Owner         string                 `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{4}
}

func (x *Scenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Scenario) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *Scenario) GetPlanHash() string {
	if x != nil {
		return x.PlanHash
	}
	return ""
}

func (x *Scenario) GetStepsJson() string {
	if x != nil {
		return x.StepsJson
	}
	return ""
}

func (x *Scenario) GetUnmatched() int64 {
	if x != nil {
		return x.Unmatched
	}
	return 0
}

func (x *Scenario) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Scenario) GetSourceRunId() string {
	if x != nil {
		return x.SourceRunId
	}
	return ""
}

func (x *Scenario) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Scenario) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Scenario) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ScenarioId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioId) Reset() {
	*x = ScenarioId{}
	mi := &file_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioId) ProtoMessage() {}

func (x *ScenarioId) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioId.ProtoReflect.Descriptor instead.
func (*ScenarioId) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{5}
}

func (x *ScenarioId) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type ListScenariosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosReq) Reset() {
	*x = ListScenariosReq{}
	mi := &file_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosReq) ProtoMessage() {}

func (x *ListScenariosReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosReq.ProtoReflect.Descriptor instead.
func (*ListScenariosReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenariosReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListScenariosReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListScenariosReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ListScenariosReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ScenarioList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioList) Reset() {
	*x = ScenarioList{}
	mi := &file_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioList) ProtoMessage() {}

func (x *ScenarioList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioList.ProtoReflect.Descriptor instead.
func (*ScenarioList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{7}
}

func (x *ScenarioList) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *ScenarioList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PromoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"` // reserved: stored, NOT executed (no scheduler in M13)
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`       // ADR-109: the promoted test inherits the promoter, not the scenario
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteReq) Reset() {
	*x = PromoteReq{}
	mi := &file_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteReq) ProtoMessage() {}

func (x *PromoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteReq.ProtoReflect.Descriptor instead.
func (*PromoteReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{8}
}

func (x *PromoteReq) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *PromoteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PromoteReq) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *PromoteReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type TestRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ScenarioId    string                 `protobuf:"bytes,2,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	PlanHash      string                 `protobuf:"bytes,3,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"` // reserved column only
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastStatus    string                 `protobuf:"bytes,7,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"` // pass | fail | ""
	LastRunId     string                 `protobuf:"bytes,8,opt,name=last_run_id,json=lastRunId,proto3" json:"last_run_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Found         bool                   `protobuf:"varint,10,opt,name=found,proto3" json:"found,omitempty"`
	Owner         string                 `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRecord) Reset() {
	*x = TestRecord{}
	mi := &file_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRecord) ProtoMessage() {}

func (x *TestRecord) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRecord.ProtoReflect.Descriptor instead.
func (*TestRecord) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{9}
}

func (x *TestRecord) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestRecord) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *TestRecord) GetPlanHash() string {
	if x != nil {
		return x.PlanHash
	}
	return ""
}

func (x *TestRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestRecord) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *TestRecord) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TestRecord) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *TestRecord) GetLastRunId() string {
	if x != nil {
		return x.LastRunId
	}
	return ""
}

func (x *TestRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TestRecord) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TestRecord) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type TestId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestId) Reset() {
	*x = TestId{}
	mi := &file_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestId) ProtoMessage() {}

func (x *TestId) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestId.ProtoReflect.Descriptor instead.
func (*TestId) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{10}
}

func (x *TestId) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type ListTestsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestsReq) Reset() {
	*x = ListTestsReq{}
	mi := &file_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestsReq) ProtoMessage() {}

func (x *ListTestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestsReq.ProtoReflect.Descriptor instead.
func (*ListTestsReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{11}
}

func (x *ListTestsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTestsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTestsReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type TestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tests         []*TestRecord          `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestList) Reset() {
	*x = TestList{}
	mi := &file_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestList) ProtoMessage() {}

func (x *TestList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestList.ProtoReflect.Descriptor instead.
func (*TestList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{12}
}

func (x *TestList) GetTests() []*TestRecord {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *TestList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- chats (BROWSABLE PROJECTION of state/conversations.db, NOT a duplicate) -
type ChatProjection struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastTarget     string                 `protobuf:"bytes,2,opt,name=last_target,json=lastTarget,proto3" json:"last_target,omitempty"`
	TurnCount      int64                  `protobuf:"varint,3,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	LastActive     string                 `protobuf:"bytes,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"` // RFC3339
	LastGoal       string                 `protobuf:"bytes,5,opt,name=last_goal,json=lastGoal,proto3" json:"last_goal,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"` // rolling summary (GAP-M9-20)
	Found          bool                   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatProjection) Reset() {
	*x = ChatProjection{}
	mi := &file_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatProjection) ProtoMessage() {}

func (x *ChatProjection) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatProjection.ProtoReflect.Descriptor instead.
func (*ChatProjection) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{13}
}

func (x *ChatProjection) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatProjection) GetLastTarget() string {
	if x != nil {
		return x.LastTarget
	}
	return ""
}

func (x *ChatProjection) GetTurnCount() int64 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *ChatProjection) GetLastActive() string {
	if x != nil {
		return x.LastActive
	}
	return ""
}

func (x *ChatProjection) GetLastGoal() string {
	if x != nil {
		return x.LastGoal
	}
	return ""
}

func (x *ChatProjection) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ChatProjection) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ChatProjection) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ConversationId struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationId) Reset() {
	*x = ConversationId{}
	mi := &file_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationId) ProtoMessage() {}

func (x *ConversationId) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationId.ProtoReflect.Descriptor instead.
func (*ConversationId) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{14}
}

func (x *ConversationId) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ListChatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsReq) Reset() {
	*x = ListChatsReq{}
	mi := &file_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsReq) ProtoMessage() {}

func (x *ListChatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsReq.ProtoReflect.Descriptor instead.
func (*ListChatsReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{15}
}

func (x *ListChatsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChatsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListChatsReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ChatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatProjection      `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatList) Reset() {
	*x = ChatList{}
	mi := &file_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatList) ProtoMessage() {}

func (x *ChatList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatList.ProtoReflect.Descriptor instead.
func (*ChatList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{16}
}

func (x *ChatList) GetChats() []*ChatProjection {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ChatList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- results (index heal-report.json / report.json) --------------------------
type ResultRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PlanId          string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Mode            string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Verdict         string                 `protobuf:"bytes,4,opt,name=verdict,proto3" json:"verdict,omitempty"` // pass | problem | regression | integrity
	ExitCode        int64                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Healed          int64                  `protobuf:"varint,6,opt,name=healed,proto3" json:"healed,omitempty"`
	Failed          int64                  `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	RegressionsJson string                 `protobuf:"bytes,8,opt,name=regressions_json,json=regressionsJson,proto3" json:"regressions_json,omitempty"`
	StepsJson       string                 `protobuf:"bytes,9,opt,name=steps_json,json=stepsJson,proto3" json:"steps_json,omitempty"`
	Coverage        float64                `protobuf:"fixed64,10,opt,name=coverage,proto3" json:"coverage,omitempty"`
	DurationMs      int64                  `protobuf:"varint,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Found           bool                   `protobuf:"varint,13,opt,name=found,proto3" json:"found,omitempty"`
	Owner           string                 `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResultRecord) Reset() {
	*x = ResultRecord{}
	mi := &file_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRecord) ProtoMessage() {}

func (x *ResultRecord) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRecord.ProtoReflect.Descriptor instead.
func (*ResultRecord) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{17}
}

func (x *ResultRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResultRecord) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ResultRecord) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ResultRecord) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ResultRecord) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ResultRecord) GetHealed() int64 {
	if x != nil {
		return x.Healed
	}
	return 0
}

func (x *ResultRecord) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ResultRecord) GetRegressionsJson() string {
	if x != nil {
		return x.RegressionsJson
	}
	return ""
}

func (x *ResultRecord) GetStepsJson() string {
	if x != nil {
		return x.StepsJson
	}
	return ""
}

func (x *ResultRecord) GetCoverage() float64 {
	if x != nil {
		return x.Coverage
	}
	return 0
}

func (x *ResultRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ResultRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResultRecord) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResultRecord) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ListResultsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsReq) Reset() {
	*x = ListResultsReq{}
	mi := &file_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsReq) ProtoMessage() {}

func (x *ListResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsReq.ProtoReflect.Descriptor instead.
func (*ListResultsReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{18}
}

func (x *ListResultsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResultsReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListResultsReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ResultList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ResultRecord        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultList) Reset() {
	*x = ResultList{}
	mi := &file_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultList) ProtoMessage() {}

func (x *ResultList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultList.ProtoReflect.Descriptor instead.
func (*ResultList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{19}
}

func (x *ResultList) GetResults() []*ResultRecord {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ResultList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- users (ADR-109: LOCAL accounts; OIDC/SSO/RBAC stay commercial per ADR-056) ---
// The gateway STORES a credential and never judges one: verification lives in control-api, which is
// already the authentication boundary and already holds the KDF (internal/identity). Putting the KDF
// here too would give one rule two implementations, which is the drift this milestone exists to remove.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // unique, the login handle
	PwHash        string                 `protobuf:"bytes,3,opt,name=pw_hash,json=pwHash,proto3" json:"pw_hash,omitempty"`     // internal/identity format; opaque to the gateway
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"` // may create and remove other accounts
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Found         bool                   `protobuf:"varint,6,opt,name=found,proto3" json:"found,omitempty"` // false => no such user (GetUser)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{20}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPwHash() string {
	if x != nil {
		return x.PwHash
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Either field identifies: login has a name, everything else has an id.
type UserRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRef) Reset() {
	*x = UserRef{}
	mi := &file_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRef) ProtoMessage() {}

func (x *UserRef) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRef.ProtoReflect.Descriptor instead.
func (*UserRef) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{21}
}

func (x *UserRef) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_store_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{22}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- metrics (time-series ingested from results; trends for M15) -------------
type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ts            float64                `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	LabelsJson    string                 `protobuf:"bytes,5,opt,name=labels_json,json=labelsJson,proto3" json:"labels_json,omitempty"`
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"` // ADR-109: inherited from the run, so a trend is one account's numbers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_store_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{23}
}

func (x *MetricPoint) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *MetricPoint) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetLabelsJson() string {
	if x != nil {
		return x.LabelsJson
	}
	return ""
}

func (x *MetricPoint) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type MetricsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*MetricPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_store_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{24}
}

func (x *MetricsBatch) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type MetricsQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SinceTs       float64                `protobuf:"fixed64,2,opt,name=since_ts,json=sinceTs,proto3" json:"since_ts,omitempty"`
	UntilTs       float64                `protobuf:"fixed64,3,opt,name=until_ts,json=untilTs,proto3" json:"until_ts,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQuery) Reset() {
	*x = MetricsQuery{}
	mi := &file_store_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQuery) ProtoMessage() {}

func (x *MetricsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQuery.ProtoReflect.Descriptor instead.
func (*MetricsQuery) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{25}
}

func (x *MetricsQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsQuery) GetSinceTs() float64 {
	if x != nil {
		return x.SinceTs
	}
	return 0
}

func (x *MetricsQuery) GetUntilTs() float64 {
	if x != nil {
		return x.UntilTs
	}
	return 0
}

func (x *MetricsQuery) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MetricsSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*MetricPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSeries) Reset() {
	*x = MetricsSeries{}
	mi := &file_store_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSeries) ProtoMessage() {}

func (x *MetricsSeries) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSeries.ProtoReflect.Descriptor instead.
func (*MetricsSeries) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{26}
}

func (x *MetricsSeries) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TrendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Window        int64                  `protobuf:"varint,2,opt,name=window,proto3" json:"window,omitempty"` // last N runs (0 => a sane default)
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`    // ADR-109: "" => every row (a machine token)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendReq) Reset() {
	*x = TrendReq{}
	mi := &file_store_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendReq) ProtoMessage() {}

func (x *TrendReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendReq.ProtoReflect.Descriptor instead.
func (*TrendReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{27}
}

func (x *TrendReq) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TrendReq) GetWindow() int64 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *TrendReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ts            float64                `protobuf:"fixed64,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_store_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{28}
}

func (x *TrendPoint) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TrendPoint) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *TrendPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TrendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrendPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendReply) Reset() {
	*x = TrendReply{}
	mi := &file_store_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendReply) ProtoMessage() {}

func (x *TrendReply) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendReply.ProtoReflect.Descriptor instead.
func (*TrendReply) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{29}
}

func (x *TrendReply) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// --- config (M11.5 PR-5, ADR-062: the SERVICE tier of the tiered config, ADR-049) -------------
// A key -> JSON document store. The standalone tier keeps using a file (brain/runconfig.py); this
// domain is what a service deployment reads at start and the setup wizard writes.
// SECRETS ARE REJECTED, not stripped: PutConfig fails with InvalidArgument when value_json carries a
// secret-shaped key anywhere in the document. Keys live in the process env, never in the store.
type ConfigRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // a JSON object; secret-shaped member names are refused
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 (defaulted on write)
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`                         // false => no such key (GetConfig)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRecord) Reset() {
	*x = ConfigRecord{}
	mi := &file_store_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRecord) ProtoMessage() {}

func (x *ConfigRecord) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRecord.ProtoReflect.Descriptor instead.
func (*ConfigRecord) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{30}
}

func (x *ConfigRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigRecord) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *ConfigRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ConfigRecord) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ConfigKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigKey) Reset() {
	*x = ConfigKey{}
	mi := &file_store_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKey) ProtoMessage() {}

func (x *ConfigKey) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKey.ProtoReflect.Descriptor instead.
func (*ConfigKey) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{31}
}

func (x *ConfigKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ConfigList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigRecord        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigList) Reset() {
	*x = ConfigList{}
	mi := &file_store_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigList) ProtoMessage() {}

func (x *ConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigList.ProtoReflect.Descriptor instead.
func (*ConfigList) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{32}
}

func (x *ConfigList) GetItems() []*ConfigRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

// --- purge (ADR-100): explicitly-invoked cleanup of stored foreign text ------------------------
// Redaction-on-write cannot help what was written BEFORE it existed (ADR-098/099 closed the trace;
// this closes the store). Cleanup here means DELETING ROWS, not blanking fields: nearly all foreign
// text in this store is INHERENT — a locator IS the page's text ({"role":"button","name":"Pay now"}),
// so blanking it would break healing rather than protect anything. See docs/DB_FOREIGN_TEXT.md.
//
// This RPC is never called automatically. It has no place in agentctl's start-of-run sweep block
// (sweepTraces/sweepLogs/sweepRuns): a swept trace is reproducible by re-running, healing history is
// not, and an automatic purge would make "the tool tidied up" indistinguishable from "evidence was
// erased".
type PurgeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required and non-empty. An empty scope is REFUSED, never taken to mean "everything".
	Tables []string `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	// Epoch seconds. 0 => no age filter (every row of the named tables). The server maps this onto
	// each table's own time column, which is REAL epoch in the heal schema and RFC3339 TEXT in M13.
	OlderThanEpoch float64 `protobuf:"fixed64,2,opt,name=older_than_epoch,json=olderThanEpoch,proto3" json:"older_than_epoch,omitempty"`
	// THE DEPLOYER'S CHOICE, and both answers are legitimate:
	//
	//	false — rows leave the queries, but THE BYTES REMAIN in freed pages (measured: modernc
	//	        sqlite v1.53.0 defaults to secure_delete=0, so a deleted row is still greppable).
	//	true  — the bytes are gone, AND SO IS RECOVERABILITY: VACUUM rewrites the file, which some
	//	        organizations must not do. We do not choose this for them.
	Vacuum        bool `protobuf:"varint,3,opt,name=vacuum,proto3" json:"vacuum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeReq) Reset() {
	*x = PurgeReq{}
	mi := &file_store_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeReq) ProtoMessage() {}

func (x *PurgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeReq.ProtoReflect.Descriptor instead.
func (*PurgeReq) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{33}
}

func (x *PurgeReq) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PurgeReq) GetOlderThanEpoch() float64 {
	if x != nil {
		return x.OlderThanEpoch
	}
	return 0
}

func (x *PurgeReq) GetVacuum() bool {
	if x != nil {
		return x.Vacuum
	}
	return false
}

type PurgeTableCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Rows          int64                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeTableCount) Reset() {
	*x = PurgeTableCount{}
	mi := &file_store_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeTableCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeTableCount) ProtoMessage() {}

func (x *PurgeTableCount) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeTableCount.ProtoReflect.Descriptor instead.
func (*PurgeTableCount) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{34}
}

func (x *PurgeTableCount) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *PurgeTableCount) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PurgeReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Counts   []*PurgeTableCount     `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	Vacuumed bool                   `protobuf:"varint,2,opt,name=vacuumed,proto3" json:"vacuumed,omitempty"`
	// Non-empty when vacuum was asked for but not performed — a skipped scrub must never be silent.
	VacuumSkipped string `protobuf:"bytes,3,opt,name=vacuum_skipped,json=vacuumSkipped,proto3" json:"vacuum_skipped,omitempty"`
	// What the caller just gave up, named out loud (ARCHITECTURE principle 7): purging healing_audit
	// blinds `agentctl calibrate`, purging healed_locators resets the heal cache, and so on.
	CapabilitiesLost []string `protobuf:"bytes,4,rep,name=capabilities_lost,json=capabilitiesLost,proto3" json:"capabilities_lost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PurgeReport) Reset() {
	*x = PurgeReport{}
	mi := &file_store_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeReport) ProtoMessage() {}

func (x *PurgeReport) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeReport.ProtoReflect.Descriptor instead.
func (*PurgeReport) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{35}
}

func (x *PurgeReport) GetCounts() []*PurgeTableCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *PurgeReport) GetVacuumed() bool {
	if x != nil {
		return x.Vacuumed
	}
	return false
}

func (x *PurgeReport) GetVacuumSkipped() string {
	if x != nil {
		return x.VacuumSkipped
	}
	return ""
}

func (x *PurgeReport) GetCapabilitiesLost() []string {
	if x != nil {
		return x.CapabilitiesLost
	}
	return nil
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x17sentinel.persistence.v1\x1a\x11persistence.proto\"\xe9\x02\n" +
	"\tRunRecord\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x18\n" +
	"\aplanner\x18\x05 \x01(\tR\aplanner\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x03R\bexitCode\x12!\n" +
	"\fartifact_dir\x18\b \x01(\tR\vartifactDir\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\v \x01(\tR\n" +
	"finishedAt\x12\x14\n" +
	"\x05found\x18\f \x01(\bR\x05found\x12\x14\n" +
	"\x05owner\x18\r \x01(\tR\x05owner\"\x1e\n" +
	"\x05RunId\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"g\n" +
	"\vListRunsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"W\n" +
	"\aRunList\x126\n" +
	"\x04runs\x18\x01 \x03(\v2\".sentinel.persistence.v1.RunRecordR\x04runs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xcf\x02\n" +
	"\bScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x19\n" +
	"\brun_mode\x18\x04 \x01(\tR\arunMode\x12\x1b\n" +
	"\tplan_hash\x18\x05 \x01(\tR\bplanHash\x12\x1d\n" +
	"\n" +
	"steps_json\x18\x06 \x01(\tR\tstepsJson\x12\x1c\n" +
	"\tunmatched\x18\a \x01(\x03R\tunmatched\x12\x12\n" +
	"\x04tags\x18\b \x01(\tR\x04tags\x12\"\n" +
	"\rsource_run_id\x18\t \x01(\tR\vsourceRunId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05found\x18\v \x01(\bR\x05found\x12\x14\n" +
	"\x05owner\x18\f \x01(\tR\x05owner\"-\n" +
	"\n" +
	"ScenarioId\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"n\n" +
	"\x10ListScenariosReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"e\n" +
	"\fScenarioList\x12?\n" +
	"\tscenarios\x18\x01 \x03(\v2!.sentinel.persistence.v1.ScenarioR\tscenarios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"s\n" +
	"\n" +
	"PromoteReq\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"\xb9\x02\n" +
	"\n" +
	"TestRecord\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1f\n" +
	"\vscenario_id\x18\x02 \x01(\tR\n" +
	"scenarioId\x12\x1b\n" +
	"\tplan_hash\x18\x03 \x01(\tR\bplanHash\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1f\n" +
	"\vlast_status\x18\a \x01(\tR\n" +
	"lastStatus\x12\x1e\n" +
	"\vlast_run_id\x18\b \x01(\tR\tlastRunId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05found\x18\n" +
	" \x01(\bR\x05found\x12\x14\n" +
	"\x05owner\x18\v \x01(\tR\x05owner\"!\n" +
	"\x06TestId\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"R\n" +
	"\fListTestsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"[\n" +
	"\bTestList\x129\n" +
	"\x05tests\x18\x01 \x03(\v2#.sentinel.persistence.v1.TestRecordR\x05tests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfd\x01\n" +
	"\x0eChatProjection\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vlast_target\x18\x02 \x01(\tR\n" +
	"lastTarget\x12\x1d\n" +
	"\n" +
	"turn_count\x18\x03 \x01(\x03R\tturnCount\x12\x1f\n" +
	"\vlast_active\x18\x04 \x01(\tR\n" +
	"lastActive\x12\x1b\n" +
	"\tlast_goal\x18\x05 \x01(\tR\blastGoal\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x14\n" +
	"\x05found\x18\a \x01(\bR\x05found\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\"9\n" +
	"\x0eConversationId\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"R\n" +
	"\fListChatsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"_\n" +
	"\bChatList\x12=\n" +
	"\x05chats\x18\x01 \x03(\v2'.sentinel.persistence.v1.ChatProjectionR\x05chats\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8b\x03\n" +
	"\fResultRecord\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x18\n" +
	"\averdict\x18\x04 \x01(\tR\averdict\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x03R\bexitCode\x12\x16\n" +
	"\x06healed\x18\x06 \x01(\x03R\x06healed\x12\x16\n" +
	"\x06failed\x18\a \x01(\x03R\x06failed\x12)\n" +
	"\x10regressions_json\x18\b \x01(\tR\x0fregressionsJson\x12\x1d\n" +
	"\n" +
	"steps_json\x18\t \x01(\tR\tstepsJson\x12\x1a\n" +
	"\bcoverage\x18\n" +
	" \x01(\x01R\bcoverage\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05found\x18\r \x01(\bR\x05found\x12\x14\n" +
	"\x05owner\x18\x0e \x01(\tR\x05owner\"T\n" +
	"\x0eListResultsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"c\n" +
	"\n" +
	"ResultList\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.sentinel.persistence.v1.ResultRecordR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9c\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\apw_hash\x18\x03 \x01(\tR\x06pwHash\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05found\x18\x06 \x01(\bR\x05found\"6\n" +
	"\aUserRef\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"U\n" +
	"\bUserList\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.sentinel.persistence.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x95\x01\n" +
	"\vMetricPoint\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x01R\x02ts\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x1f\n" +
	"\vlabels_json\x18\x05 \x01(\tR\n" +
	"labelsJson\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\"L\n" +
	"\fMetricsBatch\x12<\n" +
	"\x06points\x18\x01 \x03(\v2$.sentinel.persistence.v1.MetricPointR\x06points\"n\n" +
	"\fMetricsQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsince_ts\x18\x02 \x01(\x01R\asinceTs\x12\x19\n" +
	"\buntil_ts\x18\x03 \x01(\x01R\auntilTs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"M\n" +
	"\rMetricsSeries\x12<\n" +
	"\x06points\x18\x01 \x03(\v2$.sentinel.persistence.v1.MetricPointR\x06points\"P\n" +
	"\bTrendReq\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x16\n" +
	"\x06window\x18\x02 \x01(\x03R\x06window\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"I\n" +
	"\n" +
	"TrendPoint\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x01R\x02ts\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"I\n" +
	"\n" +
	"TrendReply\x12;\n" +
	"\x06points\x18\x01 \x03(\v2#.sentinel.persistence.v1.TrendPointR\x06points\"t\n" +
	"\fConfigRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"\x1d\n" +
	"\tConfigKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\n" +
	"ConfigList\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.sentinel.persistence.v1.ConfigRecordR\x05items\"d\n" +
	"\bPurgeReq\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\tR\x06tables\x12(\n" +
	"\x10older_than_epoch\x18\x02 \x01(\x01R\x0eolderThanEpoch\x12\x16\n" +
	"\x06vacuum\x18\x03 \x01(\bR\x06vacuum\";\n" +
	"\x0fPurgeTableCount\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x03R\x04rows\"\xbf\x01\n" +
	"\vPurgeReport\x12@\n" +
	"\x06counts\x18\x01 \x03(\v2(.sentinel.persistence.v1.PurgeTableCountR\x06counts\x12\x1a\n" +
	"\bvacuumed\x18\x02 \x01(\bR\bvacuumed\x12%\n" +
	"\x0evacuum_skipped\x18\x03 \x01(\tR\rvacuumSkipped\x12+\n" +
	"\x11capabilities_lost\x18\x04 \x03(\tR\x10capabilitiesLost2\x89\x14\n" +
	"\fStoreService\x12O\n" +
	"\tUpsertRun\x12\".sentinel.persistence.v1.RunRecord\x1a\x1e.sentinel.persistence.v1.Empty\x12L\n" +
	"\x06GetRun\x12\x1e.sentinel.persistence.v1.RunId\x1a\".sentinel.persistence.v1.RunRecord\x12R\n" +
	"\bListRuns\x12$.sentinel.persistence.v1.ListRunsReq\x1a .sentinel.persistence.v1.RunList\x12Q\n" +
	"\fSaveScenario\x12!.sentinel.persistence.v1.Scenario\x1a\x1e.sentinel.persistence.v1.Empty\x12U\n" +
	"\vGetScenario\x12#.sentinel.persistence.v1.ScenarioId\x1a!.sentinel.persistence.v1.Scenario\x12a\n" +
	"\rListScenarios\x12).sentinel.persistence.v1.ListScenariosReq\x1a%.sentinel.persistence.v1.ScenarioList\x12U\n" +
	"\x0eDeleteScenario\x12#.sentinel.persistence.v1.ScenarioId\x1a\x1e.sentinel.persistence.v1.Empty\x12W\n" +
	"\vPromoteTest\x12#.sentinel.persistence.v1.PromoteReq\x1a#.sentinel.persistence.v1.TestRecord\x12O\n" +
	"\aGetTest\x12\x1f.sentinel.persistence.v1.TestId\x1a#.sentinel.persistence.v1.TestRecord\x12U\n" +
	"\tListTests\x12%.sentinel.persistence.v1.ListTestsReq\x1a!.sentinel.persistence.v1.TestList\x12M\n" +
	"\n" +
	"DeleteTest\x12\x1f.sentinel.persistence.v1.TestId\x1a\x1e.sentinel.persistence.v1.Empty\x12U\n" +
	"\n" +
	"UpsertChat\x12'.sentinel.persistence.v1.ChatProjection\x1a\x1e.sentinel.persistence.v1.Empty\x12[\n" +
	"\aGetChat\x12'.sentinel.persistence.v1.ConversationId\x1a'.sentinel.persistence.v1.ChatProjection\x12U\n" +
	"\tListChats\x12%.sentinel.persistence.v1.ListChatsReq\x1a!.sentinel.persistence.v1.ChatList\x12U\n" +
	"\n" +
	"DeleteChat\x12'.sentinel.persistence.v1.ConversationId\x1a\x1e.sentinel.persistence.v1.Empty\x12S\n" +
	"\n" +
	"SaveResult\x12%.sentinel.persistence.v1.ResultRecord\x1a\x1e.sentinel.persistence.v1.Empty\x12R\n" +
	"\tGetResult\x12\x1e.sentinel.persistence.v1.RunId\x1a%.sentinel.persistence.v1.ResultRecord\x12[\n" +
	"\vListResults\x12'.sentinel.persistence.v1.ListResultsReq\x1a#.sentinel.persistence.v1.ResultList\x12V\n" +
	"\rIngestMetrics\x12%.sentinel.persistence.v1.MetricsBatch\x1a\x1e.sentinel.persistence.v1.Empty\x12]\n" +
	"\fQueryMetrics\x12%.sentinel.persistence.v1.MetricsQuery\x1a&.sentinel.persistence.v1.MetricsSeries\x12P\n" +
	"\x06Trends\x12!.sentinel.persistence.v1.TrendReq\x1a#.sentinel.persistence.v1.TrendReply\x12R\n" +
	"\tPutConfig\x12%.sentinel.persistence.v1.ConfigRecord\x1a\x1e.sentinel.persistence.v1.Empty\x12V\n" +
	"\tGetConfig\x12\".sentinel.persistence.v1.ConfigKey\x1a%.sentinel.persistence.v1.ConfigRecord\x12Q\n" +
	"\n" +
	"ListConfig\x12\x1e.sentinel.persistence.v1.Empty\x1a#.sentinel.persistence.v1.ConfigList\x12R\n" +
	"\fDeleteConfig\x12\".sentinel.persistence.v1.ConfigKey\x1a\x1e.sentinel.persistence.v1.Empty\x12U\n" +
	"\n" +
	"PurgeStore\x12!.sentinel.persistence.v1.PurgeReq\x1a$.sentinel.persistence.v1.PurgeReport\x12K\n" +
	"\n" +
	"UpsertUser\x12\x1d.sentinel.persistence.v1.User\x1a\x1e.sentinel.persistence.v1.Empty\x12J\n" +
	"\aGetUser\x12 .sentinel.persistence.v1.UserRef\x1a\x1d.sentinel.persistence.v1.User\x12N\n" +
	"\tListUsers\x12\x1e.sentinel.persistence.v1.Empty\x1a!.sentinel.persistence.v1.UserList\x12N\n" +
	"\n" +
	"DeleteUser\x12 .sentinel.persistence.v1.UserRef\x1a\x1e.sentinel.persistence.v1.EmptyB5Z3github.com/AlexGromer/sentinel/internal/store/pb;pbb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_store_proto_goTypes = []any{
	(*RunRecord)(nil),        // 0: sentinel.persistence.v1.RunRecord
	(*RunId)(nil),            // 1: sentinel.persistence.v1.RunId
	(*ListRunsReq)(nil),      // 2: sentinel.persistence.v1.ListRunsReq
	(*RunList)(nil),          // 3: sentinel.persistence.v1.RunList
	(*Scenario)(nil),         // 4: sentinel.persistence.v1.Scenario
	(*ScenarioId)(nil),       // 5: sentinel.persistence.v1.ScenarioId
	(*ListScenariosReq)(nil), // 6: sentinel.persistence.v1.ListScenariosReq
	(*ScenarioList)(nil),     // 7: sentinel.persistence.v1.ScenarioList
	(*PromoteReq)(nil),       // 8: sentinel.persistence.v1.PromoteReq
	(*TestRecord)(nil),       // 9: sentinel.persistence.v1.TestRecord
	(*TestId)(nil),           // 10: sentinel.persistence.v1.TestId
	(*ListTestsReq)(nil),     // 11: sentinel.persistence.v1.ListTestsReq
	(*TestList)(nil),         // 12: sentinel.persistence.v1.TestList
	(*ChatProjection)(nil),   // 13: sentinel.persistence.v1.ChatProjection
	(*ConversationId)(nil),   // 14: sentinel.persistence.v1.ConversationId
	(*ListChatsReq)(nil),     // 15: sentinel.persistence.v1.ListChatsReq
	(*ChatList)(nil),         // 16: sentinel.persistence.v1.ChatList
	(*ResultRecord)(nil),     // 17: sentinel.persistence.v1.ResultRecord
	(*ListResultsReq)(nil),   // 18: sentinel.persistence.v1.ListResultsReq
	(*ResultList)(nil),       // 19: sentinel.persistence.v1.ResultList
	(*User)(nil),             // 20: sentinel.persistence.v1.User
	(*UserRef)(nil),          // 21: sentinel.persistence.v1.UserRef
	(*UserList)(nil),         // 22: sentinel.persistence.v1.UserList
	(*MetricPoint)(nil),      // 23: sentinel.persistence.v1.MetricPoint
	(*MetricsBatch)(nil),     // 24: sentinel.persistence.v1.MetricsBatch
	(*MetricsQuery)(nil),     // 25: sentinel.persistence.v1.MetricsQuery
	(*MetricsSeries)(nil),    // 26: sentinel.persistence.v1.MetricsSeries
	(*TrendReq)(nil),         // 27: sentinel.persistence.v1.TrendReq
	(*TrendPoint)(nil),       // 28: sentinel.persistence.v1.TrendPoint
	(*TrendReply)(nil),       // 29: sentinel.persistence.v1.TrendReply
	(*ConfigRecord)(nil),     // 30: sentinel.persistence.v1.ConfigRecord
	(*ConfigKey)(nil),        // 31: sentinel.persistence.v1.ConfigKey
	(*ConfigList)(nil),       // 32: sentinel.persistence.v1.ConfigList
	(*PurgeReq)(nil),         // 33: sentinel.persistence.v1.PurgeReq
	(*PurgeTableCount)(nil),  // 34: sentinel.persistence.v1.PurgeTableCount
	(*PurgeReport)(nil),      // 35: sentinel.persistence.v1.PurgeReport
	(*Empty)(nil),            // 36: sentinel.persistence.v1.Empty
}
var file_store_proto_depIdxs = []int32{
	0,  // 0: sentinel.persistence.v1.RunList.runs:type_name -> sentinel.persistence.v1.RunRecord
	4,  // 1: sentinel.persistence.v1.ScenarioList.scenarios:type_name -> sentinel.persistence.v1.Scenario
	9,  // 2: sentinel.persistence.v1.TestList.tests:type_name -> sentinel.persistence.v1.TestRecord
	13, // 3: sentinel.persistence.v1.ChatList.chats:type_name -> sentinel.persistence.v1.ChatProjection
	17, // 4: sentinel.persistence.v1.ResultList.results:type_name -> sentinel.persistence.v1.ResultRecord
	20, // 5: sentinel.persistence.v1.UserList.users:type_name -> sentinel.persistence.v1.User
	23, // 6: sentinel.persistence.v1.MetricsBatch.points:type_name -> sentinel.persistence.v1.MetricPoint
	23, // 7: sentinel.persistence.v1.MetricsSeries.points:type_name -> sentinel.persistence.v1.MetricPoint
	28, // 8: sentinel.persistence.v1.TrendReply.points:type_name -> sentinel.persistence.v1.TrendPoint
	30, // 9: sentinel.persistence.v1.ConfigList.items:type_name -> sentinel.persistence.v1.ConfigRecord
	34, // 10: sentinel.persistence.v1.PurgeReport.counts:type_name -> sentinel.persistence.v1.PurgeTableCount
	0,  // 11: sentinel.persistence.v1.StoreService.UpsertRun:input_type -> sentinel.persistence.v1.RunRecord
	1,  // 12: sentinel.persistence.v1.StoreService.GetRun:input_type -> sentinel.persistence.v1.RunId
	2,  // 13: sentinel.persistence.v1.StoreService.ListRuns:input_type -> sentinel.persistence.v1.ListRunsReq
	4,  // 14: sentinel.persistence.v1.StoreService.SaveScenario:input_type -> sentinel.persistence.v1.Scenario
	5,  // 15: sentinel.persistence.v1.StoreService.GetScenario:input_type -> sentinel.persistence.v1.ScenarioId
	6,  // 16: sentinel.persistence.v1.StoreService.ListScenarios:input_type -> sentinel.persistence.v1.ListScenariosReq
	5,  // 17: sentinel.persistence.v1.StoreService.DeleteScenario:input_type -> sentinel.persistence.v1.ScenarioId
	8,  // 18: sentinel.persistence.v1.StoreService.PromoteTest:input_type -> sentinel.persistence.v1.PromoteReq
	10, // 19: sentinel.persistence.v1.StoreService.GetTest:input_type -> sentinel.persistence.v1.TestId
	11, // 20: sentinel.persistence.v1.StoreService.ListTests:input_type -> sentinel.persistence.v1.ListTestsReq
	10, // 21: sentinel.persistence.v1.StoreService.DeleteTest:input_type -> sentinel.persistence.v1.TestId
	13, // 22: sentinel.persistence.v1.StoreService.UpsertChat:input_type -> sentinel.persistence.v1.ChatProjection
	14, // 23: sentinel.persistence.v1.StoreService.GetChat:input_type -> sentinel.persistence.v1.ConversationId
	15, // 24: sentinel.persistence.v1.StoreService.ListChats:input_type -> sentinel.persistence.v1.ListChatsReq
	14, // 25: sentinel.persistence.v1.StoreService.DeleteChat:input_type -> sentinel.persistence.v1.ConversationId
	17, // 26: sentinel.persistence.v1.StoreService.SaveResult:input_type -> sentinel.persistence.v1.ResultRecord
	1,  // 27: sentinel.persistence.v1.StoreService.GetResult:input_type -> sentinel.persistence.v1.RunId
	18, // 28: sentinel.persistence.v1.StoreService.ListResults:input_type -> sentinel.persistence.v1.ListResultsReq
	24, // 29: sentinel.persistence.v1.StoreService.IngestMetrics:input_type -> sentinel.persistence.v1.MetricsBatch
	25, // 30: sentinel.persistence.v1.StoreService.QueryMetrics:input_type -> sentinel.persistence.v1.MetricsQuery
	27, // 31: sentinel.persistence.v1.StoreService.Trends:input_type -> sentinel.persistence.v1.TrendReq
	30, // 32: sentinel.persistence.v1.StoreService.PutConfig:input_type -> sentinel.persistence.v1.ConfigRecord
	31, // 33: sentinel.persistence.v1.StoreService.GetConfig:input_type -> sentinel.persistence.v1.ConfigKey
	36, // 34: sentinel.persistence.v1.StoreService.ListConfig:input_type -> sentinel.persistence.v1.Empty
	31, // 35: sentinel.persistence.v1.StoreService.DeleteConfig:input_type -> sentinel.persistence.v1.ConfigKey
	33, // 36: sentinel.persistence.v1.StoreService.PurgeStore:input_type -> sentinel.persistence.v1.PurgeReq
	20, // 37: sentinel.persistence.v1.StoreService.UpsertUser:input_type -> sentinel.persistence.v1.User
	21, // 38: sentinel.persistence.v1.StoreService.GetUser:input_type -> sentinel.persistence.v1.UserRef
	36, // 39: sentinel.persistence.v1.StoreService.ListUsers:input_type -> sentinel.persistence.v1.Empty
	21, // 40: sentinel.persistence.v1.StoreService.DeleteUser:input_type -> sentinel.persistence.v1.UserRef
	36, // 41: sentinel.persistence.v1.StoreService.UpsertRun:output_type -> sentinel.persistence.v1.Empty
	0,  // 42: sentinel.persistence.v1.StoreService.GetRun:output_type -> sentinel.persistence.v1.RunRecord
	3,  // 43: sentinel.persistence.v1.StoreService.ListRuns:output_type -> sentinel.persistence.v1.RunList
	36, // 44: sentinel.persistence.v1.StoreService.SaveScenario:output_type -> sentinel.persistence.v1.Empty
	4,  // 45: sentinel.persistence.v1.StoreService.GetScenario:output_type -> sentinel.persistence.v1.Scenario
	7,  // 46: sentinel.persistence.v1.StoreService.ListScenarios:output_type -> sentinel.persistence.v1.ScenarioList
	36, // 47: sentinel.persistence.v1.StoreService.DeleteScenario:output_type -> sentinel.persistence.v1.Empty
	9,  // 48: sentinel.persistence.v1.StoreService.PromoteTest:output_type -> sentinel.persistence.v1.TestRecord
	9,  // 49: sentinel.persistence.v1.StoreService.GetTest:output_type -> sentinel.persistence.v1.TestRecord
	12, // 50: sentinel.persistence.v1.StoreService.ListTests:output_type -> sentinel.persistence.v1.TestList
	36, // 51: sentinel.persistence.v1.StoreService.DeleteTest:output_type -> sentinel.persistence.v1.Empty
	36, // 52: sentinel.persistence.v1.StoreService.UpsertChat:output_type -> sentinel.persistence.v1.Empty
	13, // 53: sentinel.persistence.v1.StoreService.GetChat:output_type -> sentinel.persistence.v1.ChatProjection
	16, // 54: sentinel.persistence.v1.StoreService.ListChats:output_type -> sentinel.persistence.v1.ChatList
	36, // 55: sentinel.persistence.v1.StoreService.DeleteChat:output_type -> sentinel.persistence.v1.Empty
	36, // 56: sentinel.persistence.v1.StoreService.SaveResult:output_type -> sentinel.persistence.v1.Empty
	17, // 57: sentinel.persistence.v1.StoreService.GetResult:output_type -> sentinel.persistence.v1.ResultRecord
	19, // 58: sentinel.persistence.v1.StoreService.ListResults:output_type -> sentinel.persistence.v1.ResultList
	36, // 59: sentinel.persistence.v1.StoreService.IngestMetrics:output_type -> sentinel.persistence.v1.Empty
	26, // 60: sentinel.persistence.v1.StoreService.QueryMetrics:output_type -> sentinel.persistence.v1.MetricsSeries
	29, // 61: sentinel.persistence.v1.StoreService.Trends:output_type -> sentinel.persistence.v1.TrendReply
	36, // 62: sentinel.persistence.v1.StoreService.PutConfig:output_type -> sentinel.persistence.v1.Empty
	30, // 63: sentinel.persistence.v1.StoreService.GetConfig:output_type -> sentinel.persistence.v1.ConfigRecord
	32, // 64: sentinel.persistence.v1.StoreService.ListConfig:output_type -> sentinel.persistence.v1.ConfigList
	36, // 65: sentinel.persistence.v1.StoreService.DeleteConfig:output_type -> sentinel.persistence.v1.Empty
	35, // 66: sentinel.persistence.v1.StoreService.PurgeStore:output_type -> sentinel.persistence.v1.PurgeReport
	36, // 67: sentinel.persistence.v1.StoreService.UpsertUser:output_type -> sentinel.persistence.v1.Empty
	20, // 68: sentinel.persistence.v1.StoreService.GetUser:output_type -> sentinel.persistence.v1.User
	22, // 69: sentinel.persistence.v1.StoreService.ListUsers:output_type -> sentinel.persistence.v1.UserList
	36, // 70: sentinel.persistence.v1.StoreService.DeleteUser:output_type -> sentinel.persistence.v1.Empty
	41, // [41:71] is the sub-list for method output_type
	11, // [11:41] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	file_persistence_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
