// Sentinel StoreService (M13, ADR-049/050) — the store-gateway's 5-domain persistence contract,
// layered on top of the legacy heal/trust PersistenceService (persistence.proto) in the SAME package
// + go_package so both services live in one `pb` package and one single-writer DB (ADR-007).
// SQLite-first (portable `ON CONFLICT` SQL); a Postgres backend slots in later behind STORE_DSN
// (M13-service, M11/ADR-053). Stubs are generated for Go + Python; drift = build failure.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: store.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_UpsertRun_FullMethodName      = "/sentinel.persistence.v1.StoreService/UpsertRun"
	StoreService_GetRun_FullMethodName         = "/sentinel.persistence.v1.StoreService/GetRun"
	StoreService_ListRuns_FullMethodName       = "/sentinel.persistence.v1.StoreService/ListRuns"
	StoreService_SaveScenario_FullMethodName   = "/sentinel.persistence.v1.StoreService/SaveScenario"
	StoreService_GetScenario_FullMethodName    = "/sentinel.persistence.v1.StoreService/GetScenario"
	StoreService_ListScenarios_FullMethodName  = "/sentinel.persistence.v1.StoreService/ListScenarios"
	StoreService_DeleteScenario_FullMethodName = "/sentinel.persistence.v1.StoreService/DeleteScenario"
	StoreService_PromoteTest_FullMethodName    = "/sentinel.persistence.v1.StoreService/PromoteTest"
	StoreService_GetTest_FullMethodName        = "/sentinel.persistence.v1.StoreService/GetTest"
	StoreService_ListTests_FullMethodName      = "/sentinel.persistence.v1.StoreService/ListTests"
	StoreService_DeleteTest_FullMethodName     = "/sentinel.persistence.v1.StoreService/DeleteTest"
	StoreService_UpsertChat_FullMethodName     = "/sentinel.persistence.v1.StoreService/UpsertChat"
	StoreService_GetChat_FullMethodName        = "/sentinel.persistence.v1.StoreService/GetChat"
	StoreService_ListChats_FullMethodName      = "/sentinel.persistence.v1.StoreService/ListChats"
	StoreService_DeleteChat_FullMethodName     = "/sentinel.persistence.v1.StoreService/DeleteChat"
	StoreService_SaveResult_FullMethodName     = "/sentinel.persistence.v1.StoreService/SaveResult"
	StoreService_GetResult_FullMethodName      = "/sentinel.persistence.v1.StoreService/GetResult"
	StoreService_ListResults_FullMethodName    = "/sentinel.persistence.v1.StoreService/ListResults"
	StoreService_IngestMetrics_FullMethodName  = "/sentinel.persistence.v1.StoreService/IngestMetrics"
	StoreService_QueryMetrics_FullMethodName   = "/sentinel.persistence.v1.StoreService/QueryMetrics"
	StoreService_Trends_FullMethodName         = "/sentinel.persistence.v1.StoreService/Trends"
	StoreService_PutConfig_FullMethodName      = "/sentinel.persistence.v1.StoreService/PutConfig"
	StoreService_GetConfig_FullMethodName      = "/sentinel.persistence.v1.StoreService/GetConfig"
	StoreService_ListConfig_FullMethodName     = "/sentinel.persistence.v1.StoreService/ListConfig"
	StoreService_DeleteConfig_FullMethodName   = "/sentinel.persistence.v1.StoreService/DeleteConfig"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	// runs
	UpsertRun(ctx context.Context, in *RunRecord, opts ...grpc.CallOption) (*Empty, error)
	GetRun(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*RunRecord, error)
	ListRuns(ctx context.Context, in *ListRunsReq, opts ...grpc.CallOption) (*RunList, error)
	// scenarios / tests
	SaveScenario(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Empty, error)
	GetScenario(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error)
	ListScenarios(ctx context.Context, in *ListScenariosReq, opts ...grpc.CallOption) (*ScenarioList, error)
	DeleteScenario(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Empty, error)
	PromoteTest(ctx context.Context, in *PromoteReq, opts ...grpc.CallOption) (*TestRecord, error)
	GetTest(ctx context.Context, in *TestId, opts ...grpc.CallOption) (*TestRecord, error)
	ListTests(ctx context.Context, in *ListTestsReq, opts ...grpc.CallOption) (*TestList, error)
	DeleteTest(ctx context.Context, in *TestId, opts ...grpc.CallOption) (*Empty, error)
	// chats (projection)
	UpsertChat(ctx context.Context, in *ChatProjection, opts ...grpc.CallOption) (*Empty, error)
	GetChat(ctx context.Context, in *ConversationId, opts ...grpc.CallOption) (*ChatProjection, error)
	ListChats(ctx context.Context, in *ListChatsReq, opts ...grpc.CallOption) (*ChatList, error)
	DeleteChat(ctx context.Context, in *ConversationId, opts ...grpc.CallOption) (*Empty, error)
	// results
	SaveResult(ctx context.Context, in *ResultRecord, opts ...grpc.CallOption) (*Empty, error)
	GetResult(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*ResultRecord, error)
	ListResults(ctx context.Context, in *ListResultsReq, opts ...grpc.CallOption) (*ResultList, error)
	// metrics
	IngestMetrics(ctx context.Context, in *MetricsBatch, opts ...grpc.CallOption) (*Empty, error)
	QueryMetrics(ctx context.Context, in *MetricsQuery, opts ...grpc.CallOption) (*MetricsSeries, error)
	Trends(ctx context.Context, in *TrendReq, opts ...grpc.CallOption) (*TrendReply, error)
	// config (M11.5 PR-5)
	PutConfig(ctx context.Context, in *ConfigRecord, opts ...grpc.CallOption) (*Empty, error)
	GetConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*ConfigRecord, error)
	ListConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigList, error)
	DeleteConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*Empty, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) UpsertRun(ctx context.Context, in *RunRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_UpsertRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetRun(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*RunRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRecord)
	err := c.cc.Invoke(ctx, StoreService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListRuns(ctx context.Context, in *ListRunsReq, opts ...grpc.CallOption) (*RunList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunList)
	err := c.cc.Invoke(ctx, StoreService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SaveScenario(ctx context.Context, in *Scenario, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_SaveScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetScenario(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Scenario, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scenario)
	err := c.cc.Invoke(ctx, StoreService_GetScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListScenarios(ctx context.Context, in *ListScenariosReq, opts ...grpc.CallOption) (*ScenarioList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioList)
	err := c.cc.Invoke(ctx, StoreService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteScenario(ctx context.Context, in *ScenarioId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) PromoteTest(ctx context.Context, in *PromoteReq, opts ...grpc.CallOption) (*TestRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRecord)
	err := c.cc.Invoke(ctx, StoreService_PromoteTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetTest(ctx context.Context, in *TestId, opts ...grpc.CallOption) (*TestRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRecord)
	err := c.cc.Invoke(ctx, StoreService_GetTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListTests(ctx context.Context, in *ListTestsReq, opts ...grpc.CallOption) (*TestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestList)
	err := c.cc.Invoke(ctx, StoreService_ListTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteTest(ctx context.Context, in *TestId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpsertChat(ctx context.Context, in *ChatProjection, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_UpsertChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetChat(ctx context.Context, in *ConversationId, opts ...grpc.CallOption) (*ChatProjection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatProjection)
	err := c.cc.Invoke(ctx, StoreService_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListChats(ctx context.Context, in *ListChatsReq, opts ...grpc.CallOption) (*ChatList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatList)
	err := c.cc.Invoke(ctx, StoreService_ListChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteChat(ctx context.Context, in *ConversationId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SaveResult(ctx context.Context, in *ResultRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_SaveResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetResult(ctx context.Context, in *RunId, opts ...grpc.CallOption) (*ResultRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultRecord)
	err := c.cc.Invoke(ctx, StoreService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListResults(ctx context.Context, in *ListResultsReq, opts ...grpc.CallOption) (*ResultList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultList)
	err := c.cc.Invoke(ctx, StoreService_ListResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) IngestMetrics(ctx context.Context, in *MetricsBatch, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_IngestMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) QueryMetrics(ctx context.Context, in *MetricsQuery, opts ...grpc.CallOption) (*MetricsSeries, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsSeries)
	err := c.cc.Invoke(ctx, StoreService_QueryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Trends(ctx context.Context, in *TrendReq, opts ...grpc.CallOption) (*TrendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendReply)
	err := c.cc.Invoke(ctx, StoreService_Trends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) PutConfig(ctx context.Context, in *ConfigRecord, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_PutConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*ConfigRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigRecord)
	err := c.cc.Invoke(ctx, StoreService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigList)
	err := c.cc.Invoke(ctx, StoreService_ListConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
type StoreServiceServer interface {
	// runs
	UpsertRun(context.Context, *RunRecord) (*Empty, error)
	GetRun(context.Context, *RunId) (*RunRecord, error)
	ListRuns(context.Context, *ListRunsReq) (*RunList, error)
	// scenarios / tests
	SaveScenario(context.Context, *Scenario) (*Empty, error)
	GetScenario(context.Context, *ScenarioId) (*Scenario, error)
	ListScenarios(context.Context, *ListScenariosReq) (*ScenarioList, error)
	DeleteScenario(context.Context, *ScenarioId) (*Empty, error)
	PromoteTest(context.Context, *PromoteReq) (*TestRecord, error)
	GetTest(context.Context, *TestId) (*TestRecord, error)
	ListTests(context.Context, *ListTestsReq) (*TestList, error)
	DeleteTest(context.Context, *TestId) (*Empty, error)
	// chats (projection)
	UpsertChat(context.Context, *ChatProjection) (*Empty, error)
	GetChat(context.Context, *ConversationId) (*ChatProjection, error)
	ListChats(context.Context, *ListChatsReq) (*ChatList, error)
	DeleteChat(context.Context, *ConversationId) (*Empty, error)
	// results
	SaveResult(context.Context, *ResultRecord) (*Empty, error)
	GetResult(context.Context, *RunId) (*ResultRecord, error)
	ListResults(context.Context, *ListResultsReq) (*ResultList, error)
	// metrics
	IngestMetrics(context.Context, *MetricsBatch) (*Empty, error)
	QueryMetrics(context.Context, *MetricsQuery) (*MetricsSeries, error)
	Trends(context.Context, *TrendReq) (*TrendReply, error)
	// config (M11.5 PR-5)
	PutConfig(context.Context, *ConfigRecord) (*Empty, error)
	GetConfig(context.Context, *ConfigKey) (*ConfigRecord, error)
	ListConfig(context.Context, *Empty) (*ConfigList, error)
	DeleteConfig(context.Context, *ConfigKey) (*Empty, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) UpsertRun(context.Context, *RunRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRun not implemented")
}
func (UnimplementedStoreServiceServer) GetRun(context.Context, *RunId) (*RunRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedStoreServiceServer) ListRuns(context.Context, *ListRunsReq) (*RunList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedStoreServiceServer) SaveScenario(context.Context, *Scenario) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveScenario not implemented")
}
func (UnimplementedStoreServiceServer) GetScenario(context.Context, *ScenarioId) (*Scenario, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScenario not implemented")
}
func (UnimplementedStoreServiceServer) ListScenarios(context.Context, *ListScenariosReq) (*ScenarioList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedStoreServiceServer) DeleteScenario(context.Context, *ScenarioId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScenario not implemented")
}
func (UnimplementedStoreServiceServer) PromoteTest(context.Context, *PromoteReq) (*TestRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteTest not implemented")
}
func (UnimplementedStoreServiceServer) GetTest(context.Context, *TestId) (*TestRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTest not implemented")
}
func (UnimplementedStoreServiceServer) ListTests(context.Context, *ListTestsReq) (*TestList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTests not implemented")
}
func (UnimplementedStoreServiceServer) DeleteTest(context.Context, *TestId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTest not implemented")
}
func (UnimplementedStoreServiceServer) UpsertChat(context.Context, *ChatProjection) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertChat not implemented")
}
func (UnimplementedStoreServiceServer) GetChat(context.Context, *ConversationId) (*ChatProjection, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedStoreServiceServer) ListChats(context.Context, *ListChatsReq) (*ChatList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedStoreServiceServer) DeleteChat(context.Context, *ConversationId) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedStoreServiceServer) SaveResult(context.Context, *ResultRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveResult not implemented")
}
func (UnimplementedStoreServiceServer) GetResult(context.Context, *RunId) (*ResultRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedStoreServiceServer) ListResults(context.Context, *ListResultsReq) (*ResultList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResults not implemented")
}
func (UnimplementedStoreServiceServer) IngestMetrics(context.Context, *MetricsBatch) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMetrics not implemented")
}
func (UnimplementedStoreServiceServer) QueryMetrics(context.Context, *MetricsQuery) (*MetricsSeries, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMetrics not implemented")
}
func (UnimplementedStoreServiceServer) Trends(context.Context, *TrendReq) (*TrendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Trends not implemented")
}
func (UnimplementedStoreServiceServer) PutConfig(context.Context, *ConfigRecord) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PutConfig not implemented")
}
func (UnimplementedStoreServiceServer) GetConfig(context.Context, *ConfigKey) (*ConfigRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedStoreServiceServer) ListConfig(context.Context, *Empty) (*ConfigList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfig not implemented")
}
func (UnimplementedStoreServiceServer) DeleteConfig(context.Context, *ConfigKey) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_UpsertRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpsertRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpsertRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpsertRun(ctx, req.(*RunRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetRun(ctx, req.(*RunId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListRuns(ctx, req.(*ListRunsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SaveScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scenario)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SaveScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_SaveScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SaveScenario(ctx, req.(*Scenario))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetScenario(ctx, req.(*ScenarioId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListScenarios(ctx, req.(*ListScenariosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScenarioId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteScenario(ctx, req.(*ScenarioId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_PromoteTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).PromoteTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_PromoteTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).PromoteTest(ctx, req.(*PromoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetTest(ctx, req.(*TestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListTests(ctx, req.(*ListTestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteTest(ctx, req.(*TestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpsertChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatProjection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpsertChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpsertChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpsertChat(ctx, req.(*ChatProjection))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetChat(ctx, req.(*ConversationId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListChats(ctx, req.(*ListChatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteChat(ctx, req.(*ConversationId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SaveResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SaveResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_SaveResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SaveResult(ctx, req.(*ResultRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetResult(ctx, req.(*RunId))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListResults(ctx, req.(*ListResultsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_IngestMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).IngestMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_IngestMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).IngestMetrics(ctx, req.(*MetricsBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_QueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).QueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_QueryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).QueryMetrics(ctx, req.(*MetricsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Trends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Trends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Trends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Trends(ctx, req.(*TrendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_PutConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).PutConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_PutConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).PutConfig(ctx, req.(*ConfigRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetConfig(ctx, req.(*ConfigKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteConfig(ctx, req.(*ConfigKey))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.persistence.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertRun",
			Handler:    _StoreService_UpsertRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _StoreService_GetRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _StoreService_ListRuns_Handler,
		},
		{
			MethodName: "SaveScenario",
			Handler:    _StoreService_SaveScenario_Handler,
		},
		{
			MethodName: "GetScenario",
			Handler:    _StoreService_GetScenario_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _StoreService_ListScenarios_Handler,
		},
		{
			MethodName: "DeleteScenario",
			Handler:    _StoreService_DeleteScenario_Handler,
		},
		{
			MethodName: "PromoteTest",
			Handler:    _StoreService_PromoteTest_Handler,
		},
		{
			MethodName: "GetTest",
			Handler:    _StoreService_GetTest_Handler,
		},
		{
			MethodName: "ListTests",
			Handler:    _StoreService_ListTests_Handler,
		},
		{
			MethodName: "DeleteTest",
			Handler:    _StoreService_DeleteTest_Handler,
		},
		{
			MethodName: "UpsertChat",
			Handler:    _StoreService_UpsertChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _StoreService_GetChat_Handler,
		},
		{
			MethodName: "ListChats",
			Handler:    _StoreService_ListChats_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _StoreService_DeleteChat_Handler,
		},
		{
			MethodName: "SaveResult",
			Handler:    _StoreService_SaveResult_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _StoreService_GetResult_Handler,
		},
		{
			MethodName: "ListResults",
			Handler:    _StoreService_ListResults_Handler,
		},
		{
			MethodName: "IngestMetrics",
			Handler:    _StoreService_IngestMetrics_Handler,
		},
		{
			MethodName: "QueryMetrics",
			Handler:    _StoreService_QueryMetrics_Handler,
		},
		{
			MethodName: "Trends",
			Handler:    _StoreService_Trends_Handler,
		},
		{
			MethodName: "PutConfig",
			Handler:    _StoreService_PutConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _StoreService_GetConfig_Handler,
		},
		{
			MethodName: "ListConfig",
			Handler:    _StoreService_ListConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _StoreService_DeleteConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
