# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import persistence_pb2 as persistence__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in persistence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersistenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/Lookup',
                request_serializer=persistence__pb2.LocatorKey.SerializeToString,
                response_deserializer=persistence__pb2.LocatorRecord.FromString,
                _registered_method=True)
        self.EvictStale = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/EvictStale',
                request_serializer=persistence__pb2.EvictRequest.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveLocator = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/SaveLocator',
                request_serializer=persistence__pb2.LocatorRecord.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.BumpUsed = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/BumpUsed',
                request_serializer=persistence__pb2.LocatorKey.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.AppendAudit = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/AppendAudit',
                request_serializer=persistence__pb2.AuditRow.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveGolden = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/SaveGolden',
                request_serializer=persistence__pb2.Golden.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.GetGolden = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/GetGolden',
                request_serializer=persistence__pb2.PageKey.SerializeToString,
                response_deserializer=persistence__pb2.Golden.FromString,
                _registered_method=True)
        self.RecordStep = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/RecordStep',
                request_serializer=persistence__pb2.StepResult.SerializeToString,
                response_deserializer=persistence__pb2.Quarantine.FromString,
                _registered_method=True)
        self.IsQuarantined = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/IsQuarantined',
                request_serializer=persistence__pb2.StepKey.SerializeToString,
                response_deserializer=persistence__pb2.Quarantine.FromString,
                _registered_method=True)
        self.ClearQuarantine = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/ClearQuarantine',
                request_serializer=persistence__pb2.Empty.SerializeToString,
                response_deserializer=persistence__pb2.Count.FromString,
                _registered_method=True)
        self.AuditRows = channel.unary_unary(
                '/sentinel.persistence.v1.PersistenceService/AuditRows',
                request_serializer=persistence__pb2.Empty.SerializeToString,
                response_deserializer=persistence__pb2.AuditRowsReply.FromString,
                _registered_method=True)


class PersistenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvictStale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveLocator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BumpUsed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveGolden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGolden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsQuarantined(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearQuarantine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersistenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=persistence__pb2.LocatorKey.FromString,
                    response_serializer=persistence__pb2.LocatorRecord.SerializeToString,
            ),
            'EvictStale': grpc.unary_unary_rpc_method_handler(
                    servicer.EvictStale,
                    request_deserializer=persistence__pb2.EvictRequest.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'SaveLocator': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLocator,
                    request_deserializer=persistence__pb2.LocatorRecord.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'BumpUsed': grpc.unary_unary_rpc_method_handler(
                    servicer.BumpUsed,
                    request_deserializer=persistence__pb2.LocatorKey.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'AppendAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendAudit,
                    request_deserializer=persistence__pb2.AuditRow.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'SaveGolden': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveGolden,
                    request_deserializer=persistence__pb2.Golden.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'GetGolden': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGolden,
                    request_deserializer=persistence__pb2.PageKey.FromString,
                    response_serializer=persistence__pb2.Golden.SerializeToString,
            ),
            'RecordStep': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordStep,
                    request_deserializer=persistence__pb2.StepResult.FromString,
                    response_serializer=persistence__pb2.Quarantine.SerializeToString,
            ),
            'IsQuarantined': grpc.unary_unary_rpc_method_handler(
                    servicer.IsQuarantined,
                    request_deserializer=persistence__pb2.StepKey.FromString,
                    response_serializer=persistence__pb2.Quarantine.SerializeToString,
            ),
            'ClearQuarantine': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearQuarantine,
                    request_deserializer=persistence__pb2.Empty.FromString,
                    response_serializer=persistence__pb2.Count.SerializeToString,
            ),
            'AuditRows': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditRows,
                    request_deserializer=persistence__pb2.Empty.FromString,
                    response_serializer=persistence__pb2.AuditRowsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.persistence.v1.PersistenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.persistence.v1.PersistenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersistenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/Lookup',
            persistence__pb2.LocatorKey.SerializeToString,
            persistence__pb2.LocatorRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvictStale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/EvictStale',
            persistence__pb2.EvictRequest.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveLocator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/SaveLocator',
            persistence__pb2.LocatorRecord.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BumpUsed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/BumpUsed',
            persistence__pb2.LocatorKey.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/AppendAudit',
            persistence__pb2.AuditRow.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveGolden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/SaveGolden',
            persistence__pb2.Golden.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGolden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/GetGolden',
            persistence__pb2.PageKey.SerializeToString,
            persistence__pb2.Golden.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/RecordStep',
            persistence__pb2.StepResult.SerializeToString,
            persistence__pb2.Quarantine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsQuarantined(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/IsQuarantined',
            persistence__pb2.StepKey.SerializeToString,
            persistence__pb2.Quarantine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearQuarantine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/ClearQuarantine',
            persistence__pb2.Empty.SerializeToString,
            persistence__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.PersistenceService/AuditRows',
            persistence__pb2.Empty.SerializeToString,
            persistence__pb2.AuditRowsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
