# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runcontrol.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'runcontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10runcontrol.proto\x12\x16sentinel.runcontrol.v1\"p\n\x0fStartRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x18\n\x10plan_token_limit\x18\x02 \x01(\x03\x12\x18\n\x10heal_token_limit\x18\x03 \x01(\x03\x12\x19\n\x11total_token_limit\x18\x04 \x01(\x03\"\x1b\n\rStartRunReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"j\n\x08RunEvent\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\x15\n\rprompt_tokens\x18\x03 \x01(\x03\x12\x19\n\x11\x63ompletion_tokens\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\t\"(\n\x07\x43ontrol\x12\r\n\x05\x61\x62ort\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\".\n\x0c\x41\x62ortRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x18\n\nAbortReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x8d\x02\n\nRunControl\x12Z\n\x08StartRun\x12\'.sentinel.runcontrol.v1.StartRunRequest\x1a%.sentinel.runcontrol.v1.StartRunReply\x12P\n\x0bReportEvent\x12 .sentinel.runcontrol.v1.RunEvent\x1a\x1f.sentinel.runcontrol.v1.Control\x12Q\n\x05\x41\x62ort\x12$.sentinel.runcontrol.v1.AbortRequest\x1a\".sentinel.runcontrol.v1.AbortReplyB<Z:github.com/AlexGromer/sentinel/internal/orchestrator/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runcontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/AlexGromer/sentinel/internal/orchestrator/pb;pb'
  _globals['_STARTRUNREQUEST']._serialized_start=44
  _globals['_STARTRUNREQUEST']._serialized_end=156
  _globals['_STARTRUNREPLY']._serialized_start=158
  _globals['_STARTRUNREPLY']._serialized_end=185
  _globals['_RUNEVENT']._serialized_start=187
  _globals['_RUNEVENT']._serialized_end=293
  _globals['_CONTROL']._serialized_start=295
  _globals['_CONTROL']._serialized_end=335
  _globals['_ABORTREQUEST']._serialized_start=337
  _globals['_ABORTREQUEST']._serialized_end=383
  _globals['_ABORTREPLY']._serialized_start=385
  _globals['_ABORTREPLY']._serialized_end=409
  _globals['_RUNCONTROL']._serialized_start=412
  _globals['_RUNCONTROL']._serialized_end=681
# @@protoc_insertion_point(module_scope)
