# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runcontrol_pb2 as runcontrol__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runcontrol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/StartRun',
                request_serializer=runcontrol__pb2.StartRunRequest.SerializeToString,
                response_deserializer=runcontrol__pb2.StartRunReply.FromString,
                _registered_method=True)
        self.ReportEvent = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/ReportEvent',
                request_serializer=runcontrol__pb2.RunEvent.SerializeToString,
                response_deserializer=runcontrol__pb2.Control.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/Abort',
                request_serializer=runcontrol__pb2.AbortRequest.SerializeToString,
                response_deserializer=runcontrol__pb2.AbortReply.FromString,
                _registered_method=True)
        self.Takeover = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/Takeover',
                request_serializer=runcontrol__pb2.TakeoverRequest.SerializeToString,
                response_deserializer=runcontrol__pb2.TakeoverReply.FromString,
                _registered_method=True)
        self.Return = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/Return',
                request_serializer=runcontrol__pb2.ReturnRequest.SerializeToString,
                response_deserializer=runcontrol__pb2.ReturnReply.FromString,
                _registered_method=True)
        self.DecideMap = channel.unary_unary(
                '/sentinel.runcontrol.v1.RunControl/DecideMap',
                request_serializer=runcontrol__pb2.MapDecisionRequest.SerializeToString,
                response_deserializer=runcontrol__pb2.MapDecisionReply.FromString,
                _registered_method=True)


class RunControlServicer:
    """Missing associated documentation comment in .proto file."""

    def StartRun(self, request, context):
        """Register a run (limits set by the orchestrator from config/env).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportEvent(self, request, context):
        """brain -> orchestrator, once per node-step; the reply may instruct the brain to abort / degrade
        (M9.8 F4, ADR-054: or to PAUSE for an operator takeover via Control.takeover).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """External abort (operator / deadline).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Takeover(self, request, context):
        """M9.8 F4 (ADR-054): operator co-pilot takeover/return. Takeover sets a per-run flag; the next
        ReportEvent reply then carries Control.takeover=true, so the brain interrupt()s + persists at its
        superstep boundary (paused; the human drives the live browser via CDP). Return clears the flag, and
        the brain resumes the same checkpointer thread from exactly where it paused. External (UI/operator),
        forwarded by the control-API over its WebSocket — modelled on Abort.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Return(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideMap(self, request, context):
        """ADR-108c: the MAP GATE. After exploring, the brain reports what it found and waits for a person to
        say whether to author a test over it. DecideMap records that answer; the next ReportEvent reply
        carries it as Control.map_decision, so the brain learns of it at its own superstep boundary — the
        same shape as Takeover, and for the same reason: the orchestrator holds run state, the brain polls.

        NOT modelled as takeover/return, though that channel already exists. `return` is only meaningful
        AFTER a takeover, and "the human took the browser" is a different fact from "the human approved
        this plan". Overloading them would make the log unreadable and the two states indistinguishable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=runcontrol__pb2.StartRunRequest.FromString,
                    response_serializer=runcontrol__pb2.StartRunReply.SerializeToString,
            ),
            'ReportEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportEvent,
                    request_deserializer=runcontrol__pb2.RunEvent.FromString,
                    response_serializer=runcontrol__pb2.Control.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=runcontrol__pb2.AbortRequest.FromString,
                    response_serializer=runcontrol__pb2.AbortReply.SerializeToString,
            ),
            'Takeover': grpc.unary_unary_rpc_method_handler(
                    servicer.Takeover,
                    request_deserializer=runcontrol__pb2.TakeoverRequest.FromString,
                    response_serializer=runcontrol__pb2.TakeoverReply.SerializeToString,
            ),
            'Return': grpc.unary_unary_rpc_method_handler(
                    servicer.Return,
                    request_deserializer=runcontrol__pb2.ReturnRequest.FromString,
                    response_serializer=runcontrol__pb2.ReturnReply.SerializeToString,
            ),
            'DecideMap': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideMap,
                    request_deserializer=runcontrol__pb2.MapDecisionRequest.FromString,
                    response_serializer=runcontrol__pb2.MapDecisionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.runcontrol.v1.RunControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.runcontrol.v1.RunControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/StartRun',
            runcontrol__pb2.StartRunRequest.SerializeToString,
            runcontrol__pb2.StartRunReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/ReportEvent',
            runcontrol__pb2.RunEvent.SerializeToString,
            runcontrol__pb2.Control.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/Abort',
            runcontrol__pb2.AbortRequest.SerializeToString,
            runcontrol__pb2.AbortReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Takeover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/Takeover',
            runcontrol__pb2.TakeoverRequest.SerializeToString,
            runcontrol__pb2.TakeoverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Return(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/Return',
            runcontrol__pb2.ReturnRequest.SerializeToString,
            runcontrol__pb2.ReturnReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.runcontrol.v1.RunControl/DecideMap',
            runcontrol__pb2.MapDecisionRequest.SerializeToString,
            runcontrol__pb2.MapDecisionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
