# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import persistence_pb2 as persistence__pb2
from . import store_pb2 as store__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertRun = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/UpsertRun',
                request_serializer=store__pb2.RunRecord.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/GetRun',
                request_serializer=store__pb2.RunId.SerializeToString,
                response_deserializer=store__pb2.RunRecord.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/ListRuns',
                request_serializer=store__pb2.ListRunsReq.SerializeToString,
                response_deserializer=store__pb2.RunList.FromString,
                _registered_method=True)
        self.SaveScenario = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/SaveScenario',
                request_serializer=store__pb2.Scenario.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.GetScenario = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/GetScenario',
                request_serializer=store__pb2.ScenarioId.SerializeToString,
                response_deserializer=store__pb2.Scenario.FromString,
                _registered_method=True)
        self.ListScenarios = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/ListScenarios',
                request_serializer=store__pb2.ListScenariosReq.SerializeToString,
                response_deserializer=store__pb2.ScenarioList.FromString,
                _registered_method=True)
        self.DeleteScenario = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/DeleteScenario',
                request_serializer=store__pb2.ScenarioId.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.PromoteTest = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/PromoteTest',
                request_serializer=store__pb2.PromoteReq.SerializeToString,
                response_deserializer=store__pb2.TestRecord.FromString,
                _registered_method=True)
        self.GetTest = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/GetTest',
                request_serializer=store__pb2.TestId.SerializeToString,
                response_deserializer=store__pb2.TestRecord.FromString,
                _registered_method=True)
        self.ListTests = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/ListTests',
                request_serializer=store__pb2.ListTestsReq.SerializeToString,
                response_deserializer=store__pb2.TestList.FromString,
                _registered_method=True)
        self.DeleteTest = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/DeleteTest',
                request_serializer=store__pb2.TestId.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertChat = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/UpsertChat',
                request_serializer=store__pb2.ChatProjection.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/GetChat',
                request_serializer=store__pb2.ConversationId.SerializeToString,
                response_deserializer=store__pb2.ChatProjection.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/ListChats',
                request_serializer=store__pb2.ListChatsReq.SerializeToString,
                response_deserializer=store__pb2.ChatList.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/DeleteChat',
                request_serializer=store__pb2.ConversationId.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveResult = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/SaveResult',
                request_serializer=store__pb2.ResultRecord.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/GetResult',
                request_serializer=store__pb2.RunId.SerializeToString,
                response_deserializer=store__pb2.ResultRecord.FromString,
                _registered_method=True)
        self.ListResults = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/ListResults',
                request_serializer=store__pb2.ListResultsReq.SerializeToString,
                response_deserializer=store__pb2.ResultList.FromString,
                _registered_method=True)
        self.IngestMetrics = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/IngestMetrics',
                request_serializer=store__pb2.MetricsBatch.SerializeToString,
                response_deserializer=persistence__pb2.Empty.FromString,
                _registered_method=True)
        self.QueryMetrics = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/QueryMetrics',
                request_serializer=store__pb2.MetricsQuery.SerializeToString,
                response_deserializer=store__pb2.MetricsSeries.FromString,
                _registered_method=True)
        self.Trends = channel.unary_unary(
                '/sentinel.persistence.v1.StoreService/Trends',
                request_serializer=store__pb2.TrendReq.SerializeToString,
                response_deserializer=store__pb2.TrendReply.FromString,
                _registered_method=True)


class StoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpsertRun(self, request, context):
        """runs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveScenario(self, request, context):
        """scenarios / tests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScenarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScenario(self, request, context):
        """M14 wave W3: library mgmt, idempotent (missing id -> success)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTest(self, request, context):
        """M14 wave W3
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertChat(self, request, context):
        """chats (projection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """M14 wave W3
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveResult(self, request, context):
        """results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMetrics(self, request, context):
        """metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertRun': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRun,
                    request_deserializer=store__pb2.RunRecord.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=store__pb2.RunId.FromString,
                    response_serializer=store__pb2.RunRecord.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=store__pb2.ListRunsReq.FromString,
                    response_serializer=store__pb2.RunList.SerializeToString,
            ),
            'SaveScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveScenario,
                    request_deserializer=store__pb2.Scenario.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'GetScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScenario,
                    request_deserializer=store__pb2.ScenarioId.FromString,
                    response_serializer=store__pb2.Scenario.SerializeToString,
            ),
            'ListScenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScenarios,
                    request_deserializer=store__pb2.ListScenariosReq.FromString,
                    response_serializer=store__pb2.ScenarioList.SerializeToString,
            ),
            'DeleteScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScenario,
                    request_deserializer=store__pb2.ScenarioId.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'PromoteTest': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteTest,
                    request_deserializer=store__pb2.PromoteReq.FromString,
                    response_serializer=store__pb2.TestRecord.SerializeToString,
            ),
            'GetTest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTest,
                    request_deserializer=store__pb2.TestId.FromString,
                    response_serializer=store__pb2.TestRecord.SerializeToString,
            ),
            'ListTests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTests,
                    request_deserializer=store__pb2.ListTestsReq.FromString,
                    response_serializer=store__pb2.TestList.SerializeToString,
            ),
            'DeleteTest': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTest,
                    request_deserializer=store__pb2.TestId.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'UpsertChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertChat,
                    request_deserializer=store__pb2.ChatProjection.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=store__pb2.ConversationId.FromString,
                    response_serializer=store__pb2.ChatProjection.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=store__pb2.ListChatsReq.FromString,
                    response_serializer=store__pb2.ChatList.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=store__pb2.ConversationId.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'SaveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveResult,
                    request_deserializer=store__pb2.ResultRecord.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=store__pb2.RunId.FromString,
                    response_serializer=store__pb2.ResultRecord.SerializeToString,
            ),
            'ListResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResults,
                    request_deserializer=store__pb2.ListResultsReq.FromString,
                    response_serializer=store__pb2.ResultList.SerializeToString,
            ),
            'IngestMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMetrics,
                    request_deserializer=store__pb2.MetricsBatch.FromString,
                    response_serializer=persistence__pb2.Empty.SerializeToString,
            ),
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=store__pb2.MetricsQuery.FromString,
                    response_serializer=store__pb2.MetricsSeries.SerializeToString,
            ),
            'Trends': grpc.unary_unary_rpc_method_handler(
                    servicer.Trends,
                    request_deserializer=store__pb2.TrendReq.FromString,
                    response_serializer=store__pb2.TrendReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.persistence.v1.StoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.persistence.v1.StoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/UpsertRun',
            store__pb2.RunRecord.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/GetRun',
            store__pb2.RunId.SerializeToString,
            store__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/ListRuns',
            store__pb2.ListRunsReq.SerializeToString,
            store__pb2.RunList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/SaveScenario',
            store__pb2.Scenario.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/GetScenario',
            store__pb2.ScenarioId.SerializeToString,
            store__pb2.Scenario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/ListScenarios',
            store__pb2.ListScenariosReq.SerializeToString,
            store__pb2.ScenarioList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/DeleteScenario',
            store__pb2.ScenarioId.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/PromoteTest',
            store__pb2.PromoteReq.SerializeToString,
            store__pb2.TestRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/GetTest',
            store__pb2.TestId.SerializeToString,
            store__pb2.TestRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/ListTests',
            store__pb2.ListTestsReq.SerializeToString,
            store__pb2.TestList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/DeleteTest',
            store__pb2.TestId.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/UpsertChat',
            store__pb2.ChatProjection.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/GetChat',
            store__pb2.ConversationId.SerializeToString,
            store__pb2.ChatProjection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/ListChats',
            store__pb2.ListChatsReq.SerializeToString,
            store__pb2.ChatList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/DeleteChat',
            store__pb2.ConversationId.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/SaveResult',
            store__pb2.ResultRecord.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/GetResult',
            store__pb2.RunId.SerializeToString,
            store__pb2.ResultRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/ListResults',
            store__pb2.ListResultsReq.SerializeToString,
            store__pb2.ResultList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/IngestMetrics',
            store__pb2.MetricsBatch.SerializeToString,
            persistence__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/QueryMetrics',
            store__pb2.MetricsQuery.SerializeToString,
            store__pb2.MetricsSeries.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Trends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.persistence.v1.StoreService/Trends',
            store__pb2.TrendReq.SerializeToString,
            store__pb2.TrendReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
