// #23 (THREAT_MODEL boundary ❷ / STRIDE-E): authN for the store-gateway gRPC socket. The Unix
// socket alone (FS perms) lets any same-UID process call PersistenceService and rewrite golden /
// locator data. A per-run shared secret — generated by agentctl, handed to the gateway and the
// brain — closes that: only a caller that presents the secret in call metadata is admitted.
package store

import (
	"context"
	"crypto/subtle"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// StoreTokenMDKey is the gRPC metadata key carrying the per-run shared secret. Keys are lowercase
// per the gRPC/HTTP-2 convention; the brain's GrpcStore injects this on every call.
const StoreTokenMDKey = "x-sentinel-store-token"

// TokenAuthInterceptor returns a unary server interceptor that rejects (codes.Unauthenticated) any
// call whose metadata does not carry exactly one StoreTokenMDKey value equal to token. The compare
// is constant-time. The gateway installs it only when a token is configured (STORE_TOKEN set); with
// no token the gateway logs a warning and serves unauthenticated (offline / direct-test fallback).
func TokenAuthInterceptor(token string) grpc.UnaryServerInterceptor {
	want := []byte(token)
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		md, ok := metadata.FromIncomingContext(ctx)
		if !ok {
			return nil, status.Error(codes.Unauthenticated, "store-gateway: missing auth metadata")
		}
		vals := md.Get(StoreTokenMDKey)
		if len(vals) != 1 || subtle.ConstantTimeCompare([]byte(vals[0]), want) != 1 {
			return nil, status.Error(codes.Unauthenticated, "store-gateway: invalid store token")
		}
		return handler(ctx, req)
	}
}
