#!/bin/sh
# Regenerate Formula/sentinel.rb from a release tag + the two darwin sha256s.
#   scripts/gen-brew-formula.sh <vTAG> <darwin-amd64-sha256> <darwin-arm64-sha256>
# Called by .github/workflows/release.yml (the `homebrew` job) on each v* tag. The committed
# Formula/sentinel.rb is the placeholder produced with v0.0.0 + zero shas — `brew install` fails the
# checksum on purpose until a real signed release bumps it (the maintainer-gated E2E boundary, as M11.1).
set -eu
TAG="${1:?usage: gen-brew-formula.sh <vTAG> <amd64-sha256> <arm64-sha256>}"
AMD="${2:?missing darwin-amd64 sha256}"
ARM="${3:?missing darwin-arm64 sha256}"
VER="${TAG#v}"

cat > Formula/sentinel.rb <<EOF
# AUTO-GENERATED by scripts/gen-brew-formula.sh (release.yml homebrew job, on each v* tag). Do not hand-edit.
# This repo is its own tap:  brew tap AlexGromer/sentinel https://github.com/AlexGromer/sentinel  then  brew install sentinel
# Pre-first-release the committed values are a v0.0.0 / zero-sha256 placeholder that fails the brew checksum
# on purpose (the maintainer-gated E2E boundary as M11.1); each signed release rewrites version + url + sha256.
class Sentinel < Formula
  desc "Autonomous self-healing UI-testing agent — agentctl control-plane CLI"
  homepage "https://github.com/AlexGromer/sentinel"
  version "${VER}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/AlexGromer/sentinel/releases/download/${TAG}/sentinel-${TAG}-darwin-arm64.tar.gz"
      sha256 "${ARM}"
    end
    on_intel do
      url "https://github.com/AlexGromer/sentinel/releases/download/${TAG}/sentinel-${TAG}-darwin-amd64.tar.gz"
      sha256 "${AMD}"
    end
  end

  def install
    bin.install "agentctl"
  end

  test do
    assert_match(/\d/, shell_output("#{bin}/agentctl version"))
  end
end
EOF
echo "wrote Formula/sentinel.rb ($TAG)"
